# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
from datetime import datetime

def import_history(apps, schema_editor):
    Story = apps.get_model("story", "Story")
    StoryHistory = apps.get_model("story", "StoryHistory")
    Status = apps.get_model("story", "Status")
    date = datetime.now()
    
    status=Status.objects.get(key='Partially Validated');
    story=Story.objects.get(key='SRMF-4');
    StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-5');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-6');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-7');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-8');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-9');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-12');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-13');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-14');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-15');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-16');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-18');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-19');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-21');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='R3 Validated');story=Story.objects.get(key='SRMF-22');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='R3 Validated');story=Story.objects.get(key='SRMF-59');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='R3 Delivered');story=Story.objects.get(key='SRMF-89');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='R3 Validated');story=Story.objects.get(key='SRMF-25');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='R3 Validated');story=Story.objects.get(key='SRMF-60');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='R3 Validated');story=Story.objects.get(key='SRMF-26');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='R3 Validated');story=Story.objects.get(key='SRMF-90');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='R3 Delivered');story=Story.objects.get(key='SRMF-27');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='R3 Validated');story=Story.objects.get(key='SRMF-92');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='R3 Validated');story=Story.objects.get(key='SRMF-50');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-51');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-53');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-54');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-56');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-57');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-58');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='R3 Validated');story=Story.objects.get(key='SRMF-61');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='R3 Validated');story=Story.objects.get(key='SRMF-62');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='R3 Validated');story=Story.objects.get(key='SRMF-93');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='R3 Validated');story=Story.objects.get(key='SRMF-29');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Partially Validated');story=Story.objects.get(key='SRMF-30');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='R3 Delivered');story=Story.objects.get(key='SRMF-31');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='R3 Delivered');story=Story.objects.get(key='SRMF-63');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='R3 Validated');story=Story.objects.get(key='SRMF-32');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-76');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-77');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='R3 Validated');story=Story.objects.get(key='SRMF-78');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-79');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Partially Validated');story=Story.objects.get(key='SRMF-80');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='R3 Validated');story=Story.objects.get(key='SRMF-81');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-83');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-84');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-86');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-87');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-88');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='R3 Validated');story=Story.objects.get(key='SRMF-94');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='R3 Validated');story=Story.objects.get(key='SRMF-95');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='R3 Validated');story=Story.objects.get(key='SRMF-96');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='R3 Delivered');story=Story.objects.get(key='SRMF-97');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='R3 Validated');story=Story.objects.get(key='SRMF-98');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='R3 Validated');story=Story.objects.get(key='SRMF-99');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Partially Validated');story=Story.objects.get(key='SRMF-100');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='R3 Delivered');story=Story.objects.get(key='SRMF-101');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='R3 Validated');story=Story.objects.get(key='SRMF-102');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-103');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-104');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='R3 Validated');story=Story.objects.get(key='SRMF-105');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-106');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='R3 Validated');story=Story.objects.get(key='SRMF-107');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-108');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-109');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-110');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-111');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='R3 Validated');story=Story.objects.get(key='SRMF-113');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='R3 Validated');story=Story.objects.get(key='SRMF-114');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='R3 Validated');story=Story.objects.get(key='SRMF-117');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-119');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Blocked');story=Story.objects.get(key='SRMF-120');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Blocked');story=Story.objects.get(key='SRMF-121');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-123');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-124');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-126');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-125');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-127');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-133');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Reopened');story=Story.objects.get(key='SRMF-138');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Reopened');story=Story.objects.get(key='SRMF-139');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-140');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-141');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-142');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Blocked');story=Story.objects.get(key='SRMF-143');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-144');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Blocked');story=Story.objects.get(key='SRMF-145');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Partially Validated');story=Story.objects.get(key='SRMF-146');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-147');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='R3 Validated');story=Story.objects.get(key='SRMF-155');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Partially Validated');story=Story.objects.get(key='SRMF-156');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-157');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Blocked');story=Story.objects.get(key='SRMF-158');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='R3 Validated');story=Story.objects.get(key='SRMF-159');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-160');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Partially Validated');story=Story.objects.get(key='SRMF-162');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Partially Validated');story=Story.objects.get(key='SRMF-163');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='R3 Validated');story=Story.objects.get(key='SRMF-164');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='R3 Validated');story=Story.objects.get(key='SRMF-172');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-181');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='R3 Validated');story=Story.objects.get(key='SRMF-188');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='In Progress');story=Story.objects.get(key='SRMF-189');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='R3 Validated');story=Story.objects.get(key='SRMF-190');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-191');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='R3 Validated');story=Story.objects.get(key='SRMF-197');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='R3 Validated');story=Story.objects.get(key='SRMF-198');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='R3 Validated');story=Story.objects.get(key='SRMF-199');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Partially Validated');story=Story.objects.get(key='SRMF-214');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='R3 Delivered');story=Story.objects.get(key='SRMF-215');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-216');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Partially Validated');story=Story.objects.get(key='SRMF-217');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Partially Validated');story=Story.objects.get(key='SRMF-218');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Partially Validated');story=Story.objects.get(key='SRMF-220');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='R3 Delivered');story=Story.objects.get(key='SRMF-221');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-222');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Blocked');story=Story.objects.get(key='SRMF-223');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Blocked');story=Story.objects.get(key='SRMF-224');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Partially Validated');story=Story.objects.get(key='SRMF-226');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='R3 Validated');story=Story.objects.get(key='SRMF-227');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-228');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Blocked');story=Story.objects.get(key='SRMF-229');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Blocked');story=Story.objects.get(key='SRMF-230');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Partially Validated');story=Story.objects.get(key='SRMF-232');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Partially Validated');story=Story.objects.get(key='SRMF-233');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-234');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Partially Validated');story=Story.objects.get(key='SRMF-235');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Partially Validated');story=Story.objects.get(key='SRMF-236');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Partially Validated');story=Story.objects.get(key='SRMF-238');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Partially Validated');story=Story.objects.get(key='SRMF-239');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-240');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Partially Validated');story=Story.objects.get(key='SRMF-241');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='R3 Validated');story=Story.objects.get(key='SRMF-244');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='R3 Delivered');story=Story.objects.get(key='SRMF-245');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-246');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='R3 Validated');story=Story.objects.get(key='SRMF-247');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-252');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-253');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-254');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-255');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-256');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-257');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-258');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-259');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-260');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-261');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-262');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-263');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-264');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-265');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-266');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='In Progress');story=Story.objects.get(key='SRMF-294');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='In Progress');story=Story.objects.get(key='SRMF-296');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-297');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-298');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-299');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-300');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='In Progress');story=Story.objects.get(key='SRMF-301');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='In Progress');story=Story.objects.get(key='SRMF-302');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-303');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='In Progress');story=Story.objects.get(key='SRMF-304');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-305');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-306');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-307');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-308');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-309');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-310');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-311');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-312');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-313');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-314');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-315');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-316');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-317');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-318');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-319');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-320');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-321');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-322');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-323');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-324');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-325');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-326');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-395');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-396');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='R3 Validated');story=Story.objects.get(key='SRMF-447');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-448');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-449');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-450');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-451');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-452');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-453');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-454');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-455');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-456');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-457');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-458');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-459');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-460');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-461');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-462');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-463');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-464');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-465');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-466');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-467');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-468');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-469');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-470');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-471');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-472');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-473');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-474');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-475');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-476');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-477');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-478');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-479');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-480');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-481');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-482');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-483');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-484');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-485');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-486');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-487');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-488');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-489');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-490');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-491');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-492');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-493');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-494');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-495');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-496');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-497');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-498');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-499');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-500');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-501');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-502');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-503');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-504');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-505');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-506');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-507');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-508');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-509');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-510');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-511');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-512');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-514');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-515');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-517');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-518');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-521');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-522');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-523');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-524');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-526');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-527');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-528');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-529');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-530');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-531');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-532');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-533');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-534');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-535');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-536');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-537');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-538');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-539');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-540');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-541');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-542');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-543');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-544');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-545');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-546');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-547');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-548');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-549');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-550');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-551');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-552');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-553');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-554');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-555');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-556');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-557');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-558');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-559');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-560');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-561');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-562');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-563');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-564');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-565');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-566');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-567');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-568');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-569');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-570');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-571');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-572');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-573');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-574');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-575');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-576');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-577');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-578');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-579');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-580');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-581');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-582');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-583');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-584');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-585');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-586');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-587');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-588');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-589');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-590');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-591');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-592');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-593');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-594');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-595');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-596');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-597');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-598');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-599');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-600');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-601');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-602');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-603');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-604');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-605');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-606');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-607');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-608');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-609');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-610');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-611');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-612');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-613');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-614');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-615');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-616');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-617');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-618');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-619');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-620');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-621');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-622');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-623');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-624');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-625');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-626');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Partially Validated');story=Story.objects.get(key='SRMF-627');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Open');story=Story.objects.get(key='SRMF-628');StoryHistory(story=story,status=status,date=date).save()
    status=Status.objects.get(key='Blocked');story=Story.objects.get(key='SRMF-647');StoryHistory(story=story,status=status,date=date).save()

    
class Migration(migrations.Migration):

    dependencies = [
        ('story', '0005_auto_20150921_1742'),
    ]

    operations = [
                  migrations.RunPython(import_history),
    ]
