# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
from datetime import datetime

def import_history(apps, schema_editor):
    Story = apps.get_model("story", "Story")
    StoryHistory = apps.get_model("story", "StoryHistory")
    Status = apps.get_model("story", "Status")
    date = datetime.strptime("2015-09-18", "%Y-%m-%d")

    # ACS 1.0
    if Story.objects.filter(key='SRMF-628'): StoryHistory(story=Story.objects.filter(key='SRMF-628')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-627'): StoryHistory(story=Story.objects.filter(key='SRMF-627')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-447'): StoryHistory(story=Story.objects.filter(key='SRMF-447')[0],status=Status.objects.get(key='R3 Validated'),date=date).save()
    if Story.objects.filter(key='SRMF-257'): StoryHistory(story=Story.objects.filter(key='SRMF-257')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-256'): StoryHistory(story=Story.objects.filter(key='SRMF-256')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-255'): StoryHistory(story=Story.objects.filter(key='SRMF-255')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-254'): StoryHistory(story=Story.objects.filter(key='SRMF-254')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-253'): StoryHistory(story=Story.objects.filter(key='SRMF-253')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-252'): StoryHistory(story=Story.objects.filter(key='SRMF-252')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-199'): StoryHistory(story=Story.objects.filter(key='SRMF-199')[0],status=Status.objects.get(key='R3 Validated'),date=date).save()
    if Story.objects.filter(key='SRMF-198'): StoryHistory(story=Story.objects.filter(key='SRMF-198')[0],status=Status.objects.get(key='R3 Validated'),date=date).save()
    if Story.objects.filter(key='SRMF-197'): StoryHistory(story=Story.objects.filter(key='SRMF-197')[0],status=Status.objects.get(key='R3 Validated'),date=date).save()
    if Story.objects.filter(key='SRMF-191'): StoryHistory(story=Story.objects.filter(key='SRMF-191')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-190'): StoryHistory(story=Story.objects.filter(key='SRMF-190')[0],status=Status.objects.get(key='R3 Validated'),date=date).save()
    if Story.objects.filter(key='SRMF-189'): StoryHistory(story=Story.objects.filter(key='SRMF-189')[0],status=Status.objects.get(key='In Progress'),date=date).save()
    if Story.objects.filter(key='SRMF-188'): StoryHistory(story=Story.objects.filter(key='SRMF-188')[0],status=Status.objects.get(key='R3 Validated'),date=date).save()
    if Story.objects.filter(key='SRMF-181'): StoryHistory(story=Story.objects.filter(key='SRMF-181')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-172'): StoryHistory(story=Story.objects.filter(key='SRMF-172')[0],status=Status.objects.get(key='R3 Validated'),date=date).save()
    if Story.objects.filter(key='SRMF-164'): StoryHistory(story=Story.objects.filter(key='SRMF-164')[0],status=Status.objects.get(key='R3 Validated'),date=date).save()
    if Story.objects.filter(key='SRMF-163'): StoryHistory(story=Story.objects.filter(key='SRMF-163')[0],status=Status.objects.get(key='Partially Validated'),date=date).save()
    if Story.objects.filter(key='SRMF-162'): StoryHistory(story=Story.objects.filter(key='SRMF-162')[0],status=Status.objects.get(key='Partially Validated'),date=date).save()
    if Story.objects.filter(key='SRMF-160'): StoryHistory(story=Story.objects.filter(key='SRMF-160')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-159'): StoryHistory(story=Story.objects.filter(key='SRMF-159')[0],status=Status.objects.get(key='R3 Validated'),date=date).save()
    if Story.objects.filter(key='SRMF-158'): StoryHistory(story=Story.objects.filter(key='SRMF-158')[0],status=Status.objects.get(key='Blocked'),date=date).save()
    if Story.objects.filter(key='SRMF-157'): StoryHistory(story=Story.objects.filter(key='SRMF-157')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-156'): StoryHistory(story=Story.objects.filter(key='SRMF-156')[0],status=Status.objects.get(key='Partially Validated'),date=date).save()
    if Story.objects.filter(key='SRMF-155'): StoryHistory(story=Story.objects.filter(key='SRMF-155')[0],status=Status.objects.get(key='R3 Validated'),date=date).save()
    if Story.objects.filter(key='SRMF-147'): StoryHistory(story=Story.objects.filter(key='SRMF-147')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-146'): StoryHistory(story=Story.objects.filter(key='SRMF-146')[0],status=Status.objects.get(key='Partially Validated'),date=date).save()
    if Story.objects.filter(key='SRMF-145'): StoryHistory(story=Story.objects.filter(key='SRMF-145')[0],status=Status.objects.get(key='R3 Delivered'),date=date).save()
    if Story.objects.filter(key='SRMF-144'): StoryHistory(story=Story.objects.filter(key='SRMF-144')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-143'): StoryHistory(story=Story.objects.filter(key='SRMF-143')[0],status=Status.objects.get(key='R3 Delivered'),date=date).save()
    if Story.objects.filter(key='SRMF-142'): StoryHistory(story=Story.objects.filter(key='SRMF-142')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-141'): StoryHistory(story=Story.objects.filter(key='SRMF-141')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-140'): StoryHistory(story=Story.objects.filter(key='SRMF-140')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-139'): StoryHistory(story=Story.objects.filter(key='SRMF-139')[0],status=Status.objects.get(key='Reopened'),date=date).save()
    if Story.objects.filter(key='SRMF-138'): StoryHistory(story=Story.objects.filter(key='SRMF-138')[0],status=Status.objects.get(key='Reopened'),date=date).save()
    if Story.objects.filter(key='SRMF-133'): StoryHistory(story=Story.objects.filter(key='SRMF-133')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-123'): StoryHistory(story=Story.objects.filter(key='SRMF-123')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-121'): StoryHistory(story=Story.objects.filter(key='SRMF-121')[0],status=Status.objects.get(key='Blocked'),date=date).save()
    if Story.objects.filter(key='SRMF-120'): StoryHistory(story=Story.objects.filter(key='SRMF-120')[0],status=Status.objects.get(key='Blocked'),date=date).save()
    if Story.objects.filter(key='SRMF-117'): StoryHistory(story=Story.objects.filter(key='SRMF-117')[0],status=Status.objects.get(key='R3 Validated'),date=date).save()
    if Story.objects.filter(key='SRMF-116'): StoryHistory(story=Story.objects.filter(key='SRMF-116')[0],status=Status.objects.get(key='R3 Delivered'),date=date).save()
    if Story.objects.filter(key='SRMF-114'): StoryHistory(story=Story.objects.filter(key='SRMF-114')[0],status=Status.objects.get(key='R3 Validated'),date=date).save()
    if Story.objects.filter(key='SRMF-113'): StoryHistory(story=Story.objects.filter(key='SRMF-113')[0],status=Status.objects.get(key='R3 Validated'),date=date).save()
    if Story.objects.filter(key='SRMF-112'): StoryHistory(story=Story.objects.filter(key='SRMF-112')[0],status=Status.objects.get(key='R3 Delivered'),date=date).save()
    if Story.objects.filter(key='SRMF-111'): StoryHistory(story=Story.objects.filter(key='SRMF-111')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-110'): StoryHistory(story=Story.objects.filter(key='SRMF-110')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-109'): StoryHistory(story=Story.objects.filter(key='SRMF-109')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-108'): StoryHistory(story=Story.objects.filter(key='SRMF-108')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-107'): StoryHistory(story=Story.objects.filter(key='SRMF-107')[0],status=Status.objects.get(key='R3 Validated'),date=date).save()
    if Story.objects.filter(key='SRMF-106'): StoryHistory(story=Story.objects.filter(key='SRMF-106')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-105'): StoryHistory(story=Story.objects.filter(key='SRMF-105')[0],status=Status.objects.get(key='R3 Validated'),date=date).save()
    if Story.objects.filter(key='SRMF-104'): StoryHistory(story=Story.objects.filter(key='SRMF-104')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-103'): StoryHistory(story=Story.objects.filter(key='SRMF-103')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-102'): StoryHistory(story=Story.objects.filter(key='SRMF-102')[0],status=Status.objects.get(key='R3 Validated'),date=date).save()
    if Story.objects.filter(key='SRMF-101'): StoryHistory(story=Story.objects.filter(key='SRMF-101')[0],status=Status.objects.get(key='R3 Delivered'),date=date).save()
    if Story.objects.filter(key='SRMF-100'): StoryHistory(story=Story.objects.filter(key='SRMF-100')[0],status=Status.objects.get(key='Partially Validated'),date=date).save()
    if Story.objects.filter(key='SRMF-99'): StoryHistory(story=Story.objects.filter(key='SRMF-99')[0],status=Status.objects.get(key='R3 Validated'),date=date).save()
    if Story.objects.filter(key='SRMF-98'): StoryHistory(story=Story.objects.filter(key='SRMF-98')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-97'): StoryHistory(story=Story.objects.filter(key='SRMF-97')[0],status=Status.objects.get(key='R3 Delivered'),date=date).save()
    if Story.objects.filter(key='SRMF-96'): StoryHistory(story=Story.objects.filter(key='SRMF-96')[0],status=Status.objects.get(key='R3 Validated'),date=date).save()
    if Story.objects.filter(key='SRMF-95'): StoryHistory(story=Story.objects.filter(key='SRMF-95')[0],status=Status.objects.get(key='R3 Validated'),date=date).save()
    if Story.objects.filter(key='SRMF-94'): StoryHistory(story=Story.objects.filter(key='SRMF-94')[0],status=Status.objects.get(key='R3 Validated'),date=date).save()
    if Story.objects.filter(key='SRMF-93'): StoryHistory(story=Story.objects.filter(key='SRMF-93')[0],status=Status.objects.get(key='R3 Validated'),date=date).save()
    if Story.objects.filter(key='SRMF-92'): StoryHistory(story=Story.objects.filter(key='SRMF-92')[0],status=Status.objects.get(key='R3 Delivered'),date=date).save()
    if Story.objects.filter(key='SRMF-90'): StoryHistory(story=Story.objects.filter(key='SRMF-90')[0],status=Status.objects.get(key='R3 Validated'),date=date).save()
    if Story.objects.filter(key='SRMF-89'): StoryHistory(story=Story.objects.filter(key='SRMF-89')[0],status=Status.objects.get(key='R3 Delivered'),date=date).save()
    if Story.objects.filter(key='SRMF-81'): StoryHistory(story=Story.objects.filter(key='SRMF-81')[0],status=Status.objects.get(key='R3 Validated'),date=date).save()
    if Story.objects.filter(key='SRMF-80'): StoryHistory(story=Story.objects.filter(key='SRMF-80')[0],status=Status.objects.get(key='Partially Validated'),date=date).save()
    if Story.objects.filter(key='SRMF-79'): StoryHistory(story=Story.objects.filter(key='SRMF-79')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-78'): StoryHistory(story=Story.objects.filter(key='SRMF-78')[0],status=Status.objects.get(key='R3 Validated'),date=date).save()
    if Story.objects.filter(key='SRMF-63'): StoryHistory(story=Story.objects.filter(key='SRMF-63')[0],status=Status.objects.get(key='R3 Delivered'),date=date).save()
    if Story.objects.filter(key='SRMF-62'): StoryHistory(story=Story.objects.filter(key='SRMF-62')[0],status=Status.objects.get(key='R3 Validated'),date=date).save()
    if Story.objects.filter(key='SRMF-61'): StoryHistory(story=Story.objects.filter(key='SRMF-61')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-60'): StoryHistory(story=Story.objects.filter(key='SRMF-60')[0],status=Status.objects.get(key='R3 Validated'),date=date).save()
    if Story.objects.filter(key='SRMF-59'): StoryHistory(story=Story.objects.filter(key='SRMF-59')[0],status=Status.objects.get(key='R3 Validated'),date=date).save()
    if Story.objects.filter(key='SRMF-54'): StoryHistory(story=Story.objects.filter(key='SRMF-54')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-53'): StoryHistory(story=Story.objects.filter(key='SRMF-53')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-51'): StoryHistory(story=Story.objects.filter(key='SRMF-51')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-50'): StoryHistory(story=Story.objects.filter(key='SRMF-50')[0],status=Status.objects.get(key='R3 Validated'),date=date).save()
    if Story.objects.filter(key='SRMF-32'): StoryHistory(story=Story.objects.filter(key='SRMF-32')[0],status=Status.objects.get(key='R3 Validated'),date=date).save()
    if Story.objects.filter(key='SRMF-31'): StoryHistory(story=Story.objects.filter(key='SRMF-31')[0],status=Status.objects.get(key='R3 Delivered'),date=date).save()
    if Story.objects.filter(key='SRMF-30'): StoryHistory(story=Story.objects.filter(key='SRMF-30')[0],status=Status.objects.get(key='Partially Validated'),date=date).save()
    if Story.objects.filter(key='SRMF-29'): StoryHistory(story=Story.objects.filter(key='SRMF-29')[0],status=Status.objects.get(key='R3 Validated'),date=date).save()
    if Story.objects.filter(key='SRMF-27'): StoryHistory(story=Story.objects.filter(key='SRMF-27')[0],status=Status.objects.get(key='R3 Delivered'),date=date).save()
    if Story.objects.filter(key='SRMF-26'): StoryHistory(story=Story.objects.filter(key='SRMF-26')[0],status=Status.objects.get(key='R3 Validated'),date=date).save()
    if Story.objects.filter(key='SRMF-25'): StoryHistory(story=Story.objects.filter(key='SRMF-25')[0],status=Status.objects.get(key='R3 Validated'),date=date).save()
    if Story.objects.filter(key='SRMF-22'): StoryHistory(story=Story.objects.filter(key='SRMF-22')[0],status=Status.objects.get(key='R3 Validated'),date=date).save()
    if Story.objects.filter(key='SRMF-5'): StoryHistory(story=Story.objects.filter(key='SRMF-5')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-4'): StoryHistory(story=Story.objects.filter(key='SRMF-4')[0],status=Status.objects.get(key='Partially Validated'),date=date).save()

    # ACS 1.1
    if Story.objects.filter(key='SRMF-626'): StoryHistory(story=Story.objects.filter(key='SRMF-626')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-625'): StoryHistory(story=Story.objects.filter(key='SRMF-625')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-624'): StoryHistory(story=Story.objects.filter(key='SRMF-624')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-623'): StoryHistory(story=Story.objects.filter(key='SRMF-623')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-622'): StoryHistory(story=Story.objects.filter(key='SRMF-622')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-621'): StoryHistory(story=Story.objects.filter(key='SRMF-621')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-620'): StoryHistory(story=Story.objects.filter(key='SRMF-620')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-619'): StoryHistory(story=Story.objects.filter(key='SRMF-619')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-618'): StoryHistory(story=Story.objects.filter(key='SRMF-618')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-617'): StoryHistory(story=Story.objects.filter(key='SRMF-617')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-616'): StoryHistory(story=Story.objects.filter(key='SRMF-616')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-615'): StoryHistory(story=Story.objects.filter(key='SRMF-615')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-614'): StoryHistory(story=Story.objects.filter(key='SRMF-614')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-613'): StoryHistory(story=Story.objects.filter(key='SRMF-613')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-612'): StoryHistory(story=Story.objects.filter(key='SRMF-612')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-611'): StoryHistory(story=Story.objects.filter(key='SRMF-611')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-610'): StoryHistory(story=Story.objects.filter(key='SRMF-610')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-609'): StoryHistory(story=Story.objects.filter(key='SRMF-609')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-608'): StoryHistory(story=Story.objects.filter(key='SRMF-608')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-607'): StoryHistory(story=Story.objects.filter(key='SRMF-607')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-606'): StoryHistory(story=Story.objects.filter(key='SRMF-606')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-605'): StoryHistory(story=Story.objects.filter(key='SRMF-605')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-604'): StoryHistory(story=Story.objects.filter(key='SRMF-604')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-603'): StoryHistory(story=Story.objects.filter(key='SRMF-603')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-602'): StoryHistory(story=Story.objects.filter(key='SRMF-602')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-601'): StoryHistory(story=Story.objects.filter(key='SRMF-601')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-600'): StoryHistory(story=Story.objects.filter(key='SRMF-600')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-599'): StoryHistory(story=Story.objects.filter(key='SRMF-599')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-598'): StoryHistory(story=Story.objects.filter(key='SRMF-598')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-597'): StoryHistory(story=Story.objects.filter(key='SRMF-597')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-596'): StoryHistory(story=Story.objects.filter(key='SRMF-596')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-595'): StoryHistory(story=Story.objects.filter(key='SRMF-595')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-594'): StoryHistory(story=Story.objects.filter(key='SRMF-594')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-593'): StoryHistory(story=Story.objects.filter(key='SRMF-593')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-592'): StoryHistory(story=Story.objects.filter(key='SRMF-592')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-591'): StoryHistory(story=Story.objects.filter(key='SRMF-591')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-590'): StoryHistory(story=Story.objects.filter(key='SRMF-590')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-589'): StoryHistory(story=Story.objects.filter(key='SRMF-589')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-588'): StoryHistory(story=Story.objects.filter(key='SRMF-588')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-587'): StoryHistory(story=Story.objects.filter(key='SRMF-587')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-586'): StoryHistory(story=Story.objects.filter(key='SRMF-586')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-585'): StoryHistory(story=Story.objects.filter(key='SRMF-585')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-584'): StoryHistory(story=Story.objects.filter(key='SRMF-584')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-583'): StoryHistory(story=Story.objects.filter(key='SRMF-583')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-582'): StoryHistory(story=Story.objects.filter(key='SRMF-582')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-581'): StoryHistory(story=Story.objects.filter(key='SRMF-581')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-580'): StoryHistory(story=Story.objects.filter(key='SRMF-580')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-579'): StoryHistory(story=Story.objects.filter(key='SRMF-579')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-578'): StoryHistory(story=Story.objects.filter(key='SRMF-578')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-577'): StoryHistory(story=Story.objects.filter(key='SRMF-577')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-576'): StoryHistory(story=Story.objects.filter(key='SRMF-576')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-575'): StoryHistory(story=Story.objects.filter(key='SRMF-575')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-574'): StoryHistory(story=Story.objects.filter(key='SRMF-574')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-573'): StoryHistory(story=Story.objects.filter(key='SRMF-573')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-572'): StoryHistory(story=Story.objects.filter(key='SRMF-572')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-571'): StoryHistory(story=Story.objects.filter(key='SRMF-571')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-570'): StoryHistory(story=Story.objects.filter(key='SRMF-570')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-569'): StoryHistory(story=Story.objects.filter(key='SRMF-569')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-568'): StoryHistory(story=Story.objects.filter(key='SRMF-568')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-567'): StoryHistory(story=Story.objects.filter(key='SRMF-567')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-566'): StoryHistory(story=Story.objects.filter(key='SRMF-566')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-565'): StoryHistory(story=Story.objects.filter(key='SRMF-565')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-564'): StoryHistory(story=Story.objects.filter(key='SRMF-564')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-563'): StoryHistory(story=Story.objects.filter(key='SRMF-563')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-562'): StoryHistory(story=Story.objects.filter(key='SRMF-562')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-561'): StoryHistory(story=Story.objects.filter(key='SRMF-561')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-560'): StoryHistory(story=Story.objects.filter(key='SRMF-560')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-559'): StoryHistory(story=Story.objects.filter(key='SRMF-559')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-558'): StoryHistory(story=Story.objects.filter(key='SRMF-558')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-557'): StoryHistory(story=Story.objects.filter(key='SRMF-557')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-556'): StoryHistory(story=Story.objects.filter(key='SRMF-556')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-555'): StoryHistory(story=Story.objects.filter(key='SRMF-555')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-554'): StoryHistory(story=Story.objects.filter(key='SRMF-554')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-553'): StoryHistory(story=Story.objects.filter(key='SRMF-553')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-552'): StoryHistory(story=Story.objects.filter(key='SRMF-552')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-551'): StoryHistory(story=Story.objects.filter(key='SRMF-551')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-550'): StoryHistory(story=Story.objects.filter(key='SRMF-550')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-549'): StoryHistory(story=Story.objects.filter(key='SRMF-549')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-548'): StoryHistory(story=Story.objects.filter(key='SRMF-548')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-547'): StoryHistory(story=Story.objects.filter(key='SRMF-547')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-546'): StoryHistory(story=Story.objects.filter(key='SRMF-546')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-545'): StoryHistory(story=Story.objects.filter(key='SRMF-545')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-544'): StoryHistory(story=Story.objects.filter(key='SRMF-544')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-543'): StoryHistory(story=Story.objects.filter(key='SRMF-543')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-542'): StoryHistory(story=Story.objects.filter(key='SRMF-542')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-541'): StoryHistory(story=Story.objects.filter(key='SRMF-541')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-540'): StoryHistory(story=Story.objects.filter(key='SRMF-540')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-539'): StoryHistory(story=Story.objects.filter(key='SRMF-539')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-538'): StoryHistory(story=Story.objects.filter(key='SRMF-538')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-537'): StoryHistory(story=Story.objects.filter(key='SRMF-537')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-536'): StoryHistory(story=Story.objects.filter(key='SRMF-536')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-535'): StoryHistory(story=Story.objects.filter(key='SRMF-535')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-534'): StoryHistory(story=Story.objects.filter(key='SRMF-534')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-533'): StoryHistory(story=Story.objects.filter(key='SRMF-533')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-532'): StoryHistory(story=Story.objects.filter(key='SRMF-532')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-531'): StoryHistory(story=Story.objects.filter(key='SRMF-531')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-530'): StoryHistory(story=Story.objects.filter(key='SRMF-530')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-529'): StoryHistory(story=Story.objects.filter(key='SRMF-529')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-528'): StoryHistory(story=Story.objects.filter(key='SRMF-528')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-527'): StoryHistory(story=Story.objects.filter(key='SRMF-527')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-526'): StoryHistory(story=Story.objects.filter(key='SRMF-526')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-524'): StoryHistory(story=Story.objects.filter(key='SRMF-524')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-523'): StoryHistory(story=Story.objects.filter(key='SRMF-523')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-522'): StoryHistory(story=Story.objects.filter(key='SRMF-522')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-521'): StoryHistory(story=Story.objects.filter(key='SRMF-521')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-518'): StoryHistory(story=Story.objects.filter(key='SRMF-518')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-517'): StoryHistory(story=Story.objects.filter(key='SRMF-517')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-515'): StoryHistory(story=Story.objects.filter(key='SRMF-515')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-514'): StoryHistory(story=Story.objects.filter(key='SRMF-514')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-512'): StoryHistory(story=Story.objects.filter(key='SRMF-512')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-511'): StoryHistory(story=Story.objects.filter(key='SRMF-511')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-510'): StoryHistory(story=Story.objects.filter(key='SRMF-510')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-509'): StoryHistory(story=Story.objects.filter(key='SRMF-509')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-508'): StoryHistory(story=Story.objects.filter(key='SRMF-508')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-507'): StoryHistory(story=Story.objects.filter(key='SRMF-507')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-506'): StoryHistory(story=Story.objects.filter(key='SRMF-506')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-505'): StoryHistory(story=Story.objects.filter(key='SRMF-505')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-504'): StoryHistory(story=Story.objects.filter(key='SRMF-504')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-503'): StoryHistory(story=Story.objects.filter(key='SRMF-503')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-502'): StoryHistory(story=Story.objects.filter(key='SRMF-502')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-501'): StoryHistory(story=Story.objects.filter(key='SRMF-501')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-500'): StoryHistory(story=Story.objects.filter(key='SRMF-500')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-499'): StoryHistory(story=Story.objects.filter(key='SRMF-499')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-498'): StoryHistory(story=Story.objects.filter(key='SRMF-498')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-497'): StoryHistory(story=Story.objects.filter(key='SRMF-497')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-496'): StoryHistory(story=Story.objects.filter(key='SRMF-496')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-495'): StoryHistory(story=Story.objects.filter(key='SRMF-495')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-494'): StoryHistory(story=Story.objects.filter(key='SRMF-494')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-493'): StoryHistory(story=Story.objects.filter(key='SRMF-493')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-492'): StoryHistory(story=Story.objects.filter(key='SRMF-492')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-491'): StoryHistory(story=Story.objects.filter(key='SRMF-491')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-490'): StoryHistory(story=Story.objects.filter(key='SRMF-490')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-489'): StoryHistory(story=Story.objects.filter(key='SRMF-489')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-488'): StoryHistory(story=Story.objects.filter(key='SRMF-488')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-487'): StoryHistory(story=Story.objects.filter(key='SRMF-487')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-486'): StoryHistory(story=Story.objects.filter(key='SRMF-486')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-485'): StoryHistory(story=Story.objects.filter(key='SRMF-485')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-484'): StoryHistory(story=Story.objects.filter(key='SRMF-484')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-483'): StoryHistory(story=Story.objects.filter(key='SRMF-483')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-482'): StoryHistory(story=Story.objects.filter(key='SRMF-482')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-481'): StoryHistory(story=Story.objects.filter(key='SRMF-481')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-480'): StoryHistory(story=Story.objects.filter(key='SRMF-480')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-479'): StoryHistory(story=Story.objects.filter(key='SRMF-479')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-478'): StoryHistory(story=Story.objects.filter(key='SRMF-478')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-477'): StoryHistory(story=Story.objects.filter(key='SRMF-477')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-476'): StoryHistory(story=Story.objects.filter(key='SRMF-476')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-475'): StoryHistory(story=Story.objects.filter(key='SRMF-475')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-474'): StoryHistory(story=Story.objects.filter(key='SRMF-474')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-473'): StoryHistory(story=Story.objects.filter(key='SRMF-473')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-472'): StoryHistory(story=Story.objects.filter(key='SRMF-472')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-471'): StoryHistory(story=Story.objects.filter(key='SRMF-471')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-470'): StoryHistory(story=Story.objects.filter(key='SRMF-470')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-469'): StoryHistory(story=Story.objects.filter(key='SRMF-469')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-468'): StoryHistory(story=Story.objects.filter(key='SRMF-468')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-467'): StoryHistory(story=Story.objects.filter(key='SRMF-467')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-466'): StoryHistory(story=Story.objects.filter(key='SRMF-466')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-465'): StoryHistory(story=Story.objects.filter(key='SRMF-465')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-464'): StoryHistory(story=Story.objects.filter(key='SRMF-464')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-463'): StoryHistory(story=Story.objects.filter(key='SRMF-463')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-462'): StoryHistory(story=Story.objects.filter(key='SRMF-462')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-461'): StoryHistory(story=Story.objects.filter(key='SRMF-461')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-460'): StoryHistory(story=Story.objects.filter(key='SRMF-460')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-459'): StoryHistory(story=Story.objects.filter(key='SRMF-459')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-458'): StoryHistory(story=Story.objects.filter(key='SRMF-458')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-457'): StoryHistory(story=Story.objects.filter(key='SRMF-457')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-456'): StoryHistory(story=Story.objects.filter(key='SRMF-456')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-455'): StoryHistory(story=Story.objects.filter(key='SRMF-455')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-454'): StoryHistory(story=Story.objects.filter(key='SRMF-454')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-453'): StoryHistory(story=Story.objects.filter(key='SRMF-453')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-452'): StoryHistory(story=Story.objects.filter(key='SRMF-452')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-451'): StoryHistory(story=Story.objects.filter(key='SRMF-451')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-450'): StoryHistory(story=Story.objects.filter(key='SRMF-450')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-449'): StoryHistory(story=Story.objects.filter(key='SRMF-449')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-448'): StoryHistory(story=Story.objects.filter(key='SRMF-448')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-119'): StoryHistory(story=Story.objects.filter(key='SRMF-119')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-88'): StoryHistory(story=Story.objects.filter(key='SRMF-88')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-87'): StoryHistory(story=Story.objects.filter(key='SRMF-87')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-86'): StoryHistory(story=Story.objects.filter(key='SRMF-86')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-84'): StoryHistory(story=Story.objects.filter(key='SRMF-84')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-83'): StoryHistory(story=Story.objects.filter(key='SRMF-83')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-77'): StoryHistory(story=Story.objects.filter(key='SRMF-77')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-76'): StoryHistory(story=Story.objects.filter(key='SRMF-76')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-58'): StoryHistory(story=Story.objects.filter(key='SRMF-58')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-57'): StoryHistory(story=Story.objects.filter(key='SRMF-57')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-56'): StoryHistory(story=Story.objects.filter(key='SRMF-56')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-21'): StoryHistory(story=Story.objects.filter(key='SRMF-21')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-19'): StoryHistory(story=Story.objects.filter(key='SRMF-19')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-18'): StoryHistory(story=Story.objects.filter(key='SRMF-18')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-16'): StoryHistory(story=Story.objects.filter(key='SRMF-16')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-15'): StoryHistory(story=Story.objects.filter(key='SRMF-15')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-14'): StoryHistory(story=Story.objects.filter(key='SRMF-14')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-13'): StoryHistory(story=Story.objects.filter(key='SRMF-13')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-12'): StoryHistory(story=Story.objects.filter(key='SRMF-12')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-9'): StoryHistory(story=Story.objects.filter(key='SRMF-9')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-8'): StoryHistory(story=Story.objects.filter(key='SRMF-8')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-7'): StoryHistory(story=Story.objects.filter(key='SRMF-7')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-6'): StoryHistory(story=Story.objects.filter(key='SRMF-6')[0],status=Status.objects.get(key='Open'),date=date).save()
    
    # ACS 1.2
    if Story.objects.filter(key='SRMF-127'): StoryHistory(story=Story.objects.filter(key='SRMF-127')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-126'): StoryHistory(story=Story.objects.filter(key='SRMF-126')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-125'): StoryHistory(story=Story.objects.filter(key='SRMF-125')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-124'): StoryHistory(story=Story.objects.filter(key='SRMF-124')[0],status=Status.objects.get(key='Open'),date=date).save()
    
    # AHP
    if Story.objects.filter(key='SRMF-396'): StoryHistory(story=Story.objects.filter(key='SRMF-396')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-395'): StoryHistory(story=Story.objects.filter(key='SRMF-395')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-266'): StoryHistory(story=Story.objects.filter(key='SRMF-266')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-265'): StoryHistory(story=Story.objects.filter(key='SRMF-265')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-264'): StoryHistory(story=Story.objects.filter(key='SRMF-264')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-263'): StoryHistory(story=Story.objects.filter(key='SRMF-263')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-262'): StoryHistory(story=Story.objects.filter(key='SRMF-262')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-261'): StoryHistory(story=Story.objects.filter(key='SRMF-261')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-260'): StoryHistory(story=Story.objects.filter(key='SRMF-260')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-259'): StoryHistory(story=Story.objects.filter(key='SRMF-259')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-258'): StoryHistory(story=Story.objects.filter(key='SRMF-258')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-247'): StoryHistory(story=Story.objects.filter(key='SRMF-247')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-246'): StoryHistory(story=Story.objects.filter(key='SRMF-246')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-245'): StoryHistory(story=Story.objects.filter(key='SRMF-245')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-244'): StoryHistory(story=Story.objects.filter(key='SRMF-244')[0],status=Status.objects.get(key='R3 Delivered'),date=date).save()
    if Story.objects.filter(key='SRMF-242'): StoryHistory(story=Story.objects.filter(key='SRMF-242')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-241'): StoryHistory(story=Story.objects.filter(key='SRMF-241')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-240'): StoryHistory(story=Story.objects.filter(key='SRMF-240')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-239'): StoryHistory(story=Story.objects.filter(key='SRMF-239')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-238'): StoryHistory(story=Story.objects.filter(key='SRMF-238')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-236'): StoryHistory(story=Story.objects.filter(key='SRMF-236')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-235'): StoryHistory(story=Story.objects.filter(key='SRMF-235')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-234'): StoryHistory(story=Story.objects.filter(key='SRMF-234')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-233'): StoryHistory(story=Story.objects.filter(key='SRMF-233')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-232'): StoryHistory(story=Story.objects.filter(key='SRMF-232')[0],status=Status.objects.get(key='R3 Delivered'),date=date).save()
    if Story.objects.filter(key='SRMF-230'): StoryHistory(story=Story.objects.filter(key='SRMF-230')[0],status=Status.objects.get(key='R3 Delivered'),date=date).save()
    if Story.objects.filter(key='SRMF-229'): StoryHistory(story=Story.objects.filter(key='SRMF-229')[0],status=Status.objects.get(key='R3 Delivered'),date=date).save()
    if Story.objects.filter(key='SRMF-228'): StoryHistory(story=Story.objects.filter(key='SRMF-228')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-227'): StoryHistory(story=Story.objects.filter(key='SRMF-227')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-226'): StoryHistory(story=Story.objects.filter(key='SRMF-226')[0],status=Status.objects.get(key='R3 Delivered'),date=date).save()
    if Story.objects.filter(key='SRMF-224'): StoryHistory(story=Story.objects.filter(key='SRMF-224')[0],status=Status.objects.get(key='R3 Delivered'),date=date).save()
    if Story.objects.filter(key='SRMF-223'): StoryHistory(story=Story.objects.filter(key='SRMF-223')[0],status=Status.objects.get(key='R3 Delivered'),date=date).save()
    if Story.objects.filter(key='SRMF-222'): StoryHistory(story=Story.objects.filter(key='SRMF-222')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-221'): StoryHistory(story=Story.objects.filter(key='SRMF-221')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-220'): StoryHistory(story=Story.objects.filter(key='SRMF-220')[0],status=Status.objects.get(key='R3 Delivered'),date=date).save()
    if Story.objects.filter(key='SRMF-218'): StoryHistory(story=Story.objects.filter(key='SRMF-218')[0],status=Status.objects.get(key='R3 Delivered'),date=date).save()
    if Story.objects.filter(key='SRMF-217'): StoryHistory(story=Story.objects.filter(key='SRMF-217')[0],status=Status.objects.get(key='R3 Delivered'),date=date).save()
    if Story.objects.filter(key='SRMF-216'): StoryHistory(story=Story.objects.filter(key='SRMF-216')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-215'): StoryHistory(story=Story.objects.filter(key='SRMF-215')[0],status=Status.objects.get(key='Open'),date=date).save()
    if Story.objects.filter(key='SRMF-214'): StoryHistory(story=Story.objects.filter(key='SRMF-214')[0],status=Status.objects.get(key='R3 Delivered'),date=date).save()

class Migration(migrations.Migration):

    dependencies = [
        ('story', '0024_auto_20150922_0148'),
    ]

    operations = [
                  migrations.RunPython(import_history),
    ]
