# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
from datetime import datetime
from story.models import Story, Epic

def import_history(apps, schema_editor):
    date = datetime.strptime("2015-10-02", "%Y-%m-%d")
    
    Epic.CreateEpicFromExcel('SRMF-1', 'Creation of a new POD', 'ACS_1.0')
    Epic.CreateEpicFromExcel('SRMF-2', 'Create a new instance of ACS', 'ACS_1.0')
    Epic.CreateEpicFromExcel('SRMF-3', 'Apply and fallback bootstrap releases', 'ACS_1.1')
    Epic.CreateEpicFromExcel('SRMF-10', 'Post incident investigation', 'ACS_1.1, admin_services')
    Epic.CreateEpicFromExcel('SRMF-17', 'Display the topology of a DataCenters', 'ACS_1.1')
    Epic.CreateEpicFromExcel('SRMF-20', 'Alerting on environment issues', 'ACS_1.1')
    Epic.CreateEpicFromExcel('SRMF-33', 'Deploy a new version of an existing POD', 'ACS_1.0')
    Epic.CreateEpicFromExcel('SRMF-34', 'Dismantle an existing POD', 'ACS_1.0')
    Epic.CreateEpicFromExcel('SRMF-35', 'Create a new Isolation Zone', 'ACS_1.0')
    Epic.CreateEpicFromExcel('SRMF-36', 'Dismantle an existing Isolation Zone', 'ACS_1.0')
    Epic.CreateEpicFromExcel('SRMF-37', 'Initialize a new Datacenter', 'ACS_1.0')
    Epic.CreateEpicFromExcel('SRMF-49', 'Create a couchbase cluster', 'ACS_1.0')
    Epic.CreateEpicFromExcel('SRMF-52', 'Create an Oracle Cluster', 'ACS_1.0')
    Epic.CreateEpicFromExcel('SRMF-55', 'Administrate applications queues (LQS/GQS)', 'ACS_1.1, admin_services')
    Epic.CreateEpicFromExcel('SRMF-72', 'Check the health status of functional queues (LQS/GQS)', 'ACS_1.1')
    Epic.CreateEpicFromExcel('SRMF-73', 'Check the health status of the DataCenter', 'ACS_1.0')
    Epic.CreateEpicFromExcel('SRMF-74', 'Check the health status of an Oracle Cluster', 'ACS_1.0')
    Epic.CreateEpicFromExcel('SRMF-75', 'Check the health status of a Couchbase Cluster', 'ACS_1.0')
    Epic.CreateEpicFromExcel('SRMF-82', 'Fail-Over the Oracle instance', 'ACS_1.1')
    Epic.CreateEpicFromExcel('SRMF-85', 'Couchbase Backup', 'ACS_1.1')
    Epic.CreateEpicFromExcel('SRMF-118', 'Recover the GQS node', 'ACS_1.1')
    Epic.CreateEpicFromExcel('SRMF-128', 'Test application and fallback of couchbase releases', 'ACS_1.2')
    Epic.CreateEpicFromExcel('SRMF-129', 'Validation of Adding/removing VMs from Couchbase cluster', 'ACS_1.2')
    Epic.CreateEpicFromExcel('SRMF-134', 'Hardcode clean-up', 'ACS_1.1')
    Epic.CreateEpicFromExcel('SRMF-135', 'Apply a configuration change', 'ACS_1.0')
    Epic.CreateEpicFromExcel('SRMF-136', 'Fallback a configuration change', 'ACS_1.0')
    Epic.CreateEpicFromExcel('SRMF-137', 'Have a proper way to manage configuration specific to a given system', 'ACS_1.0')
    Epic.CreateEpicFromExcel('SRMF-152', 'Pre-requisite for ACS', 'ACS_1.0')
    Epic.CreateEpicFromExcel('SRMF-201', 'Improvements', 'ACS')
    Epic.CreateEpicFromExcel('SRMF-213', 'AHP:Shopping POD', 'AHP')
    Epic.CreateEpicFromExcel('SRMF-219', 'AHP:Booking POD', 'AHP')
    Epic.CreateEpicFromExcel('SRMF-225', 'AHP:Data Management POD', 'AHP')
    Epic.CreateEpicFromExcel('SRMF-231', 'AHP:Admin Portal POD', 'AHP')
    Epic.CreateEpicFromExcel('SRMF-237', 'AHP:CLP POD', 'AHP')
    Epic.CreateEpicFromExcel('SRMF-243', 'AHP:LSS POD', 'AHP')
    Epic.CreateEpicFromExcel('SRMF-249', 'Inject traffic internally', 'ACS_1.0')
    Epic.CreateEpicFromExcel('SRMF-250', 'Inject traffic externally', 'ACS_1.0')
    Epic.CreateEpicFromExcel('SRMF-251', 'AHP:Global Integration on ACS', 'AHP')
    Epic.CreateEpicFromExcel('SRMF-291', 'HMP - Single S-Filer Deployment', 'HMP-SRE')
    Epic.CreateEpicFromExcel('SRMF-293', 'HMP - Redundant S-Filer Deployment', 'HMP-SRE')
    Epic.CreateEpicFromExcel('SRMF-426', 'Isolate an Isolation Zone', 'ACS_1.1')
    Epic.CreateEpicFromExcel('SRMF-427', 'Resume the traffic on a Zone', 'ACS_1.1')
    Epic.CreateEpicFromExcel('SRMF-428', 'Suspend traffic to a POD', 'ACS_1.1')
    Epic.CreateEpicFromExcel('SRMF-429', 'SW Load Fallback - Resume the traffic to a POD', 'ACS_1.1')
    Epic.CreateEpicFromExcel('SRMF-430', 'Force the propagation of a `static` fileset', 'ACS_1.1')
    Epic.CreateEpicFromExcel('SRMF-433', 'Oracle Backups', 'ACS_1.1')
    Epic.CreateEpicFromExcel('SRMF-434', 'Apply an online data change (DML) on Oracle', 'ACS_1.1')
    Epic.CreateEpicFromExcel('SRMF-435', 'Fallback an online data change (DML) on Oracle', 'ACS_1.1')
    Epic.CreateEpicFromExcel('SRMF-436', 'Applying a DDL on Oracle', 'ACS_1.1')
    Epic.CreateEpicFromExcel('SRMF-437', 'Falling Back a DDL in Oracle', 'ACS_1.1')
    Epic.CreateEpicFromExcel('SRMF-438', 'Apply an online data change on Couchbase', 'ACS_1.1')
    Epic.CreateEpicFromExcel('SRMF-439', 'Fallback an online data change on Couchbase', 'ACS_1.1')
    Epic.CreateEpicFromExcel('SRMF-440', 'Applying a new view document on CouchBase', 'ACS_1.1')
    Epic.CreateEpicFromExcel('SRMF-441', 'Removing an existing view document from CouchBase', 'ACS_1.1')
    Epic.CreateEpicFromExcel('SRMF-442', 'Activate a new version of CouchBase', 'ACS_1.2')
    Epic.CreateEpicFromExcel('SRMF-443', 'Fallback an existing version of CouchBase', 'ACS_1.2')
    Epic.CreateEpicFromExcel('SRMF-444', 'Deletion of an existing set of machines from a CouchBase cluster', 'ACS_1.2')
    Epic.CreateEpicFromExcel('SRMF-445', 'Addition of a new set of machines into a CouchBase cluster', 'ACS_1.2')
    Epic.CreateEpicFromExcel('SRMF-513', 'Create a new DB component - Oracle', 'ACS_1.1')
    Epic.CreateEpicFromExcel('SRMF-516', 'Remove a DB component - Oracle', 'ACS_1.1')
    Epic.CreateEpicFromExcel('SRMF-519', 'Create new buckets - Couchbase', 'ACS_1.1')
    Epic.CreateEpicFromExcel('SRMF-520', 'Remove buckets - Couchbase', 'ACS_1.1')
    Epic.CreateEpicFromExcel('SRMF-525', 'Capability to configure the framework', 'ACS_1.1')
    Epic.CreateEpicFromExcel('SRMF-663', 'SW Load Fallback - Isolate/Resume traffic on a RU', 'ACS_1.1')
    Story.CreateHistoryFromExcel('SRMF-4', 'Test successful creation of new ACS instance', '','2 - High Attention','Create a new instance of ACS', 'Partially Validated', date)
    Story.CreateHistoryFromExcel('SRMF-5', 'Test failed creation of new ACS instance', 'CMD','3 - Normal','Create a new instance of ACS', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-6', 'Test successful framework release upgrade (Load)', 'CMD','3 - Normal','Apply and fallback bootstrap releases', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-7', 'Test successful framework release downgrade (Fallback)', 'CMD','3 - Normal','Apply and fallback bootstrap releases', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-8', 'Test failed framework release upgrade (Load)', 'CMD','3 - Normal','Apply and fallback bootstrap releases', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-9', 'Test failed framework release downgrade (Fallback)', 'CMD','3 - Normal','Apply and fallback bootstrap releases', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-12', 'Search logs for OBE flow', 'MNR, admin_services','2 - High Attention','Post incident investigation', 'R3 Delivered', date)
    Story.CreateHistoryFromExcel('SRMF-13', 'Search logs for Admin portal flow', 'MNR, admin_services','2 - High Attention','Post incident investigation', 'R3 Delivered', date)
    Story.CreateHistoryFromExcel('SRMF-14', 'Validate logs retention period', 'MNR, admin_services','4 - Low','Post incident investigation', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-15', 'Validate logs search criteria', 'MNR, admin_services','4 - Low','Post incident investigation', 'R3 Delivered', date)
    Story.CreateHistoryFromExcel('SRMF-16', 'Test availability of past search results', 'MNR, admin_services','4 - Low','Post incident investigation', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-18', 'Display Isolation zone topology', 'MNR, SRO','3 - Normal','Display the topology of a DataCenters', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-19', 'Display POD topology', 'SRO','3 - Normal','Display the topology of a DataCenters', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-21', 'Test detection of core dump', 'MNR','4 - Low','Alerting on environment issues', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-22', 'OTF-SvcBE:Create an instance of a new POD containing it', '','2 - High Attention','Creation of a new POD', 'R3 Validated', date)
    Story.CreateHistoryFromExcel('SRMF-59', 'OTF-SvcBE:Create several instances of a pod containing it', '','2 - High Attention','Creation of a new POD', 'R3 Validated', date)
    Story.CreateHistoryFromExcel('SRMF-89', 'OTF-SvcBE:Application check-out failing', 'AHP, CMD, SRO','2 - High Attention','Creation of a new POD', 'R3 Delivered', date)
    Story.CreateHistoryFromExcel('SRMF-25', 'JBoss:Create an instance of a new POD', '','2 - High Attention','Creation of a new POD', 'R3 Validated', date)
    Story.CreateHistoryFromExcel('SRMF-60', 'JBoss:Create several instances of a POD containing it', '','2 - High Attention','Creation of a new POD', 'R3 Validated', date)
    Story.CreateHistoryFromExcel('SRMF-26', 'Apache:Create an instance of a new POD', '','3 - Normal','Creation of a new POD', 'R3 Validated', date)
    Story.CreateHistoryFromExcel('SRMF-90', 'Apache:Create several instances of a POD containing it', '','3 - Normal','Creation of a new POD', 'R3 Validated', date)
    Story.CreateHistoryFromExcel('SRMF-27', 'GQSDaemon:Create an instance of a new POD', 'AHP, CMD, SRO','2 - High Attention','Creation of a new POD', 'R3 Delivered', date)
    Story.CreateHistoryFromExcel('SRMF-92', 'TimeInitDaemon:Create an instance of a POD containing it', '','2 - High Attention','Creation of a new POD', 'R3 Validated', date)
    Story.CreateHistoryFromExcel('SRMF-50', 'Couchbase cluster creation suceed', '','2 - High Attention','Create a couchbase cluster', 'R3 Validated', date)
    Story.CreateHistoryFromExcel('SRMF-51', 'Couchbase cluster creation failed', 'CMD','2 - High Attention','Create a couchbase cluster', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-53', 'Oracle cluster creation succeeded', 'CMD, SRE','2 - High Attention','Create an Oracle Cluster', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-54', 'Oracle cluster creation failed', 'CMD, SRE','2 - High Attention','Create an Oracle Cluster', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-56', 'Count item in a queue', 'MNR, Queues','3 - Normal','Administrate applications queues (LQS/GQS)', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-57', 'Purge queue with truncate', 'Queues','3 - Normal','Administrate applications queues (LQS/GQS)', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-58', 'Delete a given item in the queue', 'Queues','3 - Normal','Administrate applications queues (LQS/GQS)', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-61', 'RepeatableDaemon:Create several instances of a POD containing it', '','2 - High Attention','Creation of a new POD', 'R3 Validated', date)
    Story.CreateHistoryFromExcel('SRMF-62', 'UniqueDaemon:Create an instance of a POD containing it', '','2 - High Attention','Creation of a new POD', 'R3 Validated', date)
    Story.CreateHistoryFromExcel('SRMF-93', 'UniqueDaemon:Create the POD with several instance', '','2 - High Attention','Creation of a new POD', 'R3 Validated', date)
    Story.CreateHistoryFromExcel('SRMF-29', 'Logging Pod:Create several instances of a POD containing it', '','2 - High Attention','Creation of a new POD', 'R3 Validated', date)
    Story.CreateHistoryFromExcel('SRMF-30', 'AcsServer:Create an instance of a new POD', '','2 - High Attention','Creation of a new POD', 'Partially Validated', date)
    Story.CreateHistoryFromExcel('SRMF-31', 'GQS:Create an instance of a new POD', 'AHP, CMD, SRO','2 - High Attention','Creation of a new POD', 'R3 Delivered', date)
    Story.CreateHistoryFromExcel('SRMF-63', 'GQS:Create the POD with several instance', 'AHP, CMD, SRO','2 - High Attention','Creation of a new POD', 'R3 Delivered', date)
    Story.CreateHistoryFromExcel('SRMF-32', 'G-ESB:Create an instance of a new POD type', '','2 - High Attention','Creation of a new POD', 'R3 Validated', date)
    Story.CreateHistoryFromExcel('SRMF-76', 'Check functional queues metrics are displayed in a graph', 'Queues','2 - High Attention','Check the health status of functional queues (LQS/GQS)', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-77', 'Check functional queues status is provided', 'Queues','2 - High Attention','Check the health status of functional queues (LQS/GQS)', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-78', 'Check couchbase metrics', '','2 - High Attention','Check the health status of a Couchbase Cluster', 'R3 Validated', date)
    Story.CreateHistoryFromExcel('SRMF-79', 'Check Oracle metrics', 'MNR, SRE','2 - High Attention','Check the health status of an Oracle Cluster', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-80', 'Check service health', '','2 - High Attention','Check the health status of the DataCenter', 'Partially Validated', date)
    Story.CreateHistoryFromExcel('SRMF-81', 'Check system metrics', '','2 - High Attention','Check the health status of the DataCenter', 'R3 Validated', date)
    Story.CreateHistoryFromExcel('SRMF-83', 'Role switch successful', 'SRE','4 - Low','Fail-Over the Oracle instance', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-84', 'Role switch failed', 'SRE','4 - Low','Fail-Over the Oracle instance', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-86', 'List Available Couchbase Backup', 'DataStore','4 - Low','Couchbase Backup', 'R3 Delivered', date)
    Story.CreateHistoryFromExcel('SRMF-87', 'Backup a Couchbase instance', 'DataStore','4 - Low','Couchbase Backup', 'R3 Delivered', date)
    Story.CreateHistoryFromExcel('SRMF-88', 'Restore a Couchbase instance', 'DataStore','4 - Low','Couchbase Backup', 'R3 Delivered', date)
    Story.CreateHistoryFromExcel('SRMF-94', 'OTF-BE:Dismantle a POD', '','2 - High Attention','Dismantle an existing POD', 'R3 Validated', date)
    Story.CreateHistoryFromExcel('SRMF-95', 'JBoss:Dismantle a POD', '','2 - High Attention','Dismantle an existing POD', 'R3 Validated', date)
    Story.CreateHistoryFromExcel('SRMF-96', 'Apache:Dismantle a POD', '','3 - Normal','Dismantle an existing POD', 'R3 Validated', date)
    Story.CreateHistoryFromExcel('SRMF-97', 'GQSDaemon:Dismantle a POD containing it', 'AHP, CMD, SRO','2 - High Attention','Dismantle an existing POD', 'R3 Delivered', date)
    Story.CreateHistoryFromExcel('SRMF-98', 'UniqueDaemon:Dismantle a POD containing it', '','2 - High Attention','Dismantle an existing POD', 'R3 Validated', date)
    Story.CreateHistoryFromExcel('SRMF-99', 'Logging POD:Dismantle a POD', '','2 - High Attention','Dismantle an existing POD', 'R3 Validated', date)
    Story.CreateHistoryFromExcel('SRMF-100', 'AcsServer:Dismantle a POD', '','2 - High Attention','Dismantle an existing POD', 'Partially Validated', date)
    Story.CreateHistoryFromExcel('SRMF-101', 'GQS:Dismantle a POD', 'AHP, CMD, SRO','2 - High Attention','Dismantle an existing POD', 'R3 Delivered', date)
    Story.CreateHistoryFromExcel('SRMF-102', 'G-ESB:Dismantle a POD', '','2 - High Attention','Dismantle an existing POD', 'R3 Validated', date)
    Story.CreateHistoryFromExcel('SRMF-103', 'OTF-SvcBE:Deploy a new version of POD', 'AHP, CMD, SRO','2 - High Attention','Deploy a new version of an existing POD', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-104', 'JBoss:Deploy a new version of POD', 'AHP, CMD, SRO','2 - High Attention','Deploy a new version of an existing POD', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-105', 'Apache:Deploy a new version of POD', '','3 - Normal','Deploy a new version of an existing POD', 'R3 Validated', date)
    Story.CreateHistoryFromExcel('SRMF-106', 'GQSDaemon:Deploy a new version of POD containing it', 'AHP, CMD, SRO','2 - High Attention','Deploy a new version of an existing POD', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-107', 'UniqueDaemon:Deploy a new version of POD', '','2 - High Attention','Deploy a new version of an existing POD', 'R3 Validated', date)
    Story.CreateHistoryFromExcel('SRMF-108', 'Logserver POD:Deploy a new version of POD', 'AHP, CMD, SRO','2 - High Attention','Deploy a new version of an existing POD', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-109', 'AcsServer:Deploy a new version of POD', 'CMD, SRO','2 - High Attention','Deploy a new version of an existing POD', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-110', 'GQS:Deploy a new version of POD', 'AHP, CMD, SRO','2 - High Attention','Deploy a new version of an existing POD', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-111', 'G-ESB:Deploy a new version of POD', 'AHP, CMD, SRO','2 - High Attention','Deploy a new version of an existing POD', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-113', 'ServiceRegistery:Create a new POD', '','2 - High Attention','Creation of a new POD', 'R3 Validated', date)
    Story.CreateHistoryFromExcel('SRMF-114', 'ServiceRegistery:Create the POD with several instances', '','2 - High Attention','Creation of a new POD', 'R3 Validated', date)
    Story.CreateHistoryFromExcel('SRMF-117', 'Initialize a Datacenter', '','2 - High Attention','Initialize a new Datacenter', 'R3 Validated', date)
    Story.CreateHistoryFromExcel('SRMF-119', 'Restart of the process', 'Queues','4 - Low','Recover the GQS node', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-120', 'FDF:Create an instance of a new POD', 'AHP, CMD, SRO','2 - High Attention','Creation of a new POD', 'Blocked', date)
    Story.CreateHistoryFromExcel('SRMF-121', 'FDF:Create several instances of a POD containing it', 'AHP, CMD, SRO','2 - High Attention','Creation of a new POD', 'Blocked', date)
    Story.CreateHistoryFromExcel('SRMF-123', 'ServiceRegistery:Deploy a new version of POD', 'CMD, SRO','2 - High Attention','Deploy a new version of an existing POD', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-124', 'Addition of a new set of machines into a CouchBase cluster', 'CMD, DataStore','4 - Low','Validation of Adding/removing VMs from Couchbase cluster', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-126', 'Activate a new version of CouchBase', 'CMD, DataStore','4 - Low','Test application and fallback of couchbase releases', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-125', 'Deletion of an existing set of machines from a CouchBase cluster', 'CMD, DataStore','4 - Low','Validation of Adding/removing VMs from Couchbase cluster', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-127', 'Fallback an existing version of CouchBase', 'CMD, DataStore','4 - Low','Test application and fallback of couchbase releases', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-133', 'Isolation Zone deployment failure', 'CMD, SRO','3 - Normal','Create a new Isolation Zone', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-138', 'Change internal traffic routing', 'CMD, SRO','2 - High Attention','Apply a configuration change', 'Reopened', date)
    Story.CreateHistoryFromExcel('SRMF-139', 'Change client call settings', 'CMD, SRO','2 - High Attention','Apply a configuration change', 'Reopened', date)
    Story.CreateHistoryFromExcel('SRMF-140', 'Change client call settings', 'CMD, SRO','2 - High Attention','Fallback a configuration change', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-141', 'Change internal traffic routing', 'CMD, SRO','2 - High Attention','Fallback a configuration change', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-142', 'Target proper \'master\' files for FDF depending on environment', 'CMD, SRO','2 - High Attention','Have a proper way to manage configuration specific to a given system', 'R3 Delivered', date)
    Story.CreateHistoryFromExcel('SRMF-143', 'Be able to change Oracle password', 'CMD, SRE, SRO','3 - Normal','Have a proper way to manage configuration specific to a given system', 'Blocked', date)
    Story.CreateHistoryFromExcel('SRMF-144', 'Be able to change CouchBase password', 'CMD, SRO','3 - Normal','Have a proper way to manage configuration specific to a given system', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-145', 'Change tnsnames.ora files', 'CMD, SRE, SRO','3 - Normal','Have a proper way to manage configuration specific to a given system', 'Blocked', date)
    Story.CreateHistoryFromExcel('SRMF-146', 'Have CouchBase cluster registered in the Service Registry', '','2 - High Attention','Create a couchbase cluster', 'Partially Validated', date)
    Story.CreateHistoryFromExcel('SRMF-147', 'Have Oracle registered in the Service Registry', 'CMD, SRE, SRO','2 - High Attention','Create an Oracle Cluster', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-155', 'Test injection of external traffic (from outside the stack)', '','2 - High Attention','Create a new Isolation Zone', 'R3 Validated', date)
    Story.CreateHistoryFromExcel('SRMF-156', 'Create an Isolation Zone (DUM OBE)', '','2 - High Attention','Create a new Isolation Zone', 'Partially Validated', date)
    Story.CreateHistoryFromExcel('SRMF-157', 'FDF:Deploy a new version of POD', 'AHP, CMD, SRO','2 - High Attention','Deploy a new version of an existing POD', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-158', 'FDF:Dismantle a POD', 'AHP, CMD, SRO','2 - High Attention','Dismantle an existing POD', 'Blocked', date)
    Story.CreateHistoryFromExcel('SRMF-159', 'APA:Dismantle a POD', '','2 - High Attention','Dismantle an existing POD', 'R3 Validated', date)
    Story.CreateHistoryFromExcel('SRMF-160', 'APA:Deploy a new version of POD', 'AHP, CMD, SRO','2 - High Attention','Deploy a new version of an existing POD', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-162', 'APA:Create the POD with several instances', '','2 - High Attention','Creation of a new POD', 'Partially Validated', date)
    Story.CreateHistoryFromExcel('SRMF-163', 'APA:Create an instance of a new POD', '','2 - High Attention','Creation of a new POD', 'Partially Validated', date)
    Story.CreateHistoryFromExcel('SRMF-164', 'Dismantle an Isolation Zone (DUM OBE)', '','2 - High Attention','Dismantle an existing Isolation Zone', 'R3 Validated', date)
    Story.CreateHistoryFromExcel('SRMF-172', 'Service registry: Dismantle an existing pod', '','2 - High Attention','Dismantle an existing POD', 'R3 Validated', date)
    Story.CreateHistoryFromExcel('SRMF-181', 'Get status on Puppet job(s)', 'CMD','3 - Normal','Create a new instance of ACS', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-188', 'Bad Blueprint : Invalid json format', '','3 - Normal','Creation of a new POD', 'R3 Validated', date)
    Story.CreateHistoryFromExcel('SRMF-189', 'Bad Blueprint : Missing mandatory parameter in blueprint', 'SRO','3 - Normal','Creation of a new POD', 'In Progress', date)
    Story.CreateHistoryFromExcel('SRMF-190', 'Bad Blueprint : Bad data types in blueprint', '','3 - Normal','Creation of a new POD', 'R3 Validated', date)
    Story.CreateHistoryFromExcel('SRMF-191', 'Bad Blueprint : Inconsistencies between POD/Service blueprints of a given component', 'SRO','3 - Normal','Creation of a new POD', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-197', 'Injection from within the OShift cluster (continuous injection)', '','2 - High Attention','Create a new Isolation Zone', 'R3 Validated', date)
    Story.CreateHistoryFromExcel('SRMF-198', 'Test injection of external traffic (from within the stack)', '','2 - High Attention','Create a new Isolation Zone', 'R3 Validated', date)
    Story.CreateHistoryFromExcel('SRMF-199', 'Injection from within the OShift cluster (single message)', '','2 - High Attention','Create a new Isolation Zone', 'R3 Validated', date)
    Story.CreateHistoryFromExcel('SRMF-214', 'AHP:Create a new Shopping POD - single instance', '','2 - High Attention','AHP:Shopping POD', 'Partially Validated', date)
    Story.CreateHistoryFromExcel('SRMF-215', 'AHP:Create a new Shopping POD - multi instance', 'AHP, CMD, SRO','2 - High Attention','AHP:Shopping POD', 'R3 Delivered', date)
    Story.CreateHistoryFromExcel('SRMF-216', 'AHP:Load a new version of Shopping POD', 'AHP, CMD, SRO','2 - High Attention','AHP:Shopping POD', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-217', 'AHP:Inject traffic internally on the Shopping POD', '','2 - High Attention','AHP:Shopping POD', 'Partially Validated', date)
    Story.CreateHistoryFromExcel('SRMF-218', 'AHP:Inject traffic externally on Shopping POD', '','2 - High Attention','AHP:Shopping POD', 'Partially Validated', date)
    Story.CreateHistoryFromExcel('SRMF-220', 'AHP:Create a new Booking POD - single instance', '','2 - High Attention','AHP:Booking POD', 'Partially Validated', date)
    Story.CreateHistoryFromExcel('SRMF-221', 'AHP:Create a new Booking POD - multi instance', 'AHP, CMD, SRO','2 - High Attention','AHP:Booking POD', 'R3 Delivered', date)
    Story.CreateHistoryFromExcel('SRMF-222', 'AHP:Load a new version of Booking POD', 'AHP, CMD, SRO','2 - High Attention','AHP:Booking POD', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-223', 'AHP:Inject traffic internally on the Booking POD', 'AHP, CMD, SRO','2 - High Attention','AHP:Booking POD', 'Blocked', date)
    Story.CreateHistoryFromExcel('SRMF-224', 'AHP:Inject traffic externally on Booking POD', 'AHP, CMD, SRO','2 - High Attention','AHP:Booking POD', 'Blocked', date)
    Story.CreateHistoryFromExcel('SRMF-226', 'AHP:Create a new Data Management POD - single instance', '','2 - High Attention','AHP:Data Management POD', 'Partially Validated', date)
    Story.CreateHistoryFromExcel('SRMF-227', 'AHP:Create a new Data Management POD - multi instance', '','2 - High Attention','AHP:Data Management POD', 'R3 Validated', date)
    Story.CreateHistoryFromExcel('SRMF-228', 'AHP:Load a new version of Data Management POD', 'AHP, CMD, SRO','2 - High Attention','AHP:Data Management POD', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-229', 'AHP:Inject traffic internally on the Data Management POD', 'AHP, CMD, SRO','2 - High Attention','AHP:Data Management POD', 'Blocked', date)
    Story.CreateHistoryFromExcel('SRMF-230', 'AHP:Inject traffic externally on the Data Management POD', 'AHP, CMD, SRO','2 - High Attention','AHP:Data Management POD', 'Blocked', date)
    Story.CreateHistoryFromExcel('SRMF-232', 'AHP:Create a new Admin Portal POD - single instance', '','2 - High Attention','AHP:Admin Portal POD', 'Partially Validated', date)
    Story.CreateHistoryFromExcel('SRMF-233', 'AHP:Create a new Admin Portal POD - multi instance', '','2 - High Attention','AHP:Admin Portal POD', 'Partially Validated', date)
    Story.CreateHistoryFromExcel('SRMF-234', 'AHP:Load a new version of Admin Portal POD', 'AHP, CMD, SRO','2 - High Attention','AHP:Admin Portal POD', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-235', 'AHP:Inject traffic internally on the Admin Portal POD', '','2 - High Attention','AHP:Admin Portal POD', 'Partially Validated', date)
    Story.CreateHistoryFromExcel('SRMF-236', 'AHP:Inject traffic externally on Admin Portal POD', '','2 - High Attention','AHP:Admin Portal POD', 'Partially Validated', date)
    Story.CreateHistoryFromExcel('SRMF-238', 'AHP:Create a new CLP POD - single instance', '','2 - High Attention','AHP:CLP POD', 'Partially Validated', date)
    Story.CreateHistoryFromExcel('SRMF-239', 'AHP:Create a new CLP POD - multi instance', '','2 - High Attention','AHP:CLP POD', 'Partially Validated', date)
    Story.CreateHistoryFromExcel('SRMF-240', 'AHP:Load a new version of CLP POD', 'AHP, CMD, SRO','2 - High Attention','AHP:CLP POD', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-241', 'AHP:Inject traffic internally on the CLP POD', '','2 - High Attention','AHP:CLP POD', 'Partially Validated', date)
    Story.CreateHistoryFromExcel('SRMF-244', 'AHP:Create a new LSS POD - single instance', '','2 - High Attention','AHP:LSS POD', 'R3 Validated', date)
    Story.CreateHistoryFromExcel('SRMF-245', 'AHP:Create a new LSS POD - multi instance', 'AHP, CMD, SRO','2 - High Attention','AHP:LSS POD', 'R3 Delivered', date)
    Story.CreateHistoryFromExcel('SRMF-246', 'AHP:Load a new version of LSS POD', 'AHP, CMD, SRO','2 - High Attention','AHP:LSS POD', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-247', 'AHP:Inject traffic internally on LSS POD', '','2 - High Attention','AHP:LSS POD', 'R3 Validated', date)
    Story.CreateHistoryFromExcel('SRMF-258', 'AHP:Create a new instance of the whole AHP', 'AHP, CMD, SRO','2 - High Attention','AHP:Global Integration on ACS', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-259', 'AHP:Load a new instance of the whole AHP', 'AHP, CMD, SRO','2 - High Attention','AHP:Global Integration on ACS', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-260', 'AHP:Monitoring is defined for AHP', 'SRE','3 - Normal','AHP:Global Integration on ACS', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-261', 'AHP:Monitoring dashboard is implemented', 'MNR, SRE','2 - High Attention','AHP:Global Integration on ACS', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-262', 'AHP:Capabillity to track what version is loaded where ?', 'AHP, CMD, SRO','3 - Normal','AHP:Global Integration on ACS', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-263', 'AHP:Log search', 'CMD, MNR','2 - High Attention','AHP:Global Integration on ACS', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-264', 'AHP:Define a way to get all admin UIs on the gateway', 'AHP, CMD, DevExp, SRO','3 - Normal','AHP:Global Integration on ACS', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-265', 'AHP:Clean-up and Security validation of the bootstrap', 'CMD, SRE, SRO','3 - Normal','AHP:Global Integration on ACS', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-266', 'AHP:Create pseudo tooling for load', 'SRE','4 - Low','AHP:Global Integration on ACS', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-294', 'Determine Proper Tenant for S-Filer', 'HMP-SRE','To Be Assessed','HMP - Single S-Filer Deployment', 'In Progress', date)
    Story.CreateHistoryFromExcel('SRMF-296', 'Create S-Filer ACS Installer', 'HMP-SRE','To Be Assessed','HMP - Single S-Filer Deployment', 'In Progress', date)
    Story.CreateHistoryFromExcel('SRMF-297', 'Deploy an S-Filer Server', 'HMP-SRE','To Be Assessed','HMP - Single S-Filer Deployment', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-298', 'Dismantle an S-Filer Server', 'HMP-SRE','To Be Assessed','HMP - Single S-Filer Deployment', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-299', 'Deploy an S-Filer Gateway', 'HMP-SRE','To Be Assessed','HMP - Single S-Filer Deployment', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-300', 'Dismantle an S-Filer Gateway', 'HMP-SRE','To Be Assessed','HMP - Single S-Filer Deployment', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-301', 'Document S-Filer Configuration', 'HMP-SRE','To Be Assessed','HMP - Single S-Filer Deployment', 'In Progress', date)
    Story.CreateHistoryFromExcel('SRMF-302', 'Backup S-Filer Configuration', 'HMP-SRE','To Be Assessed','HMP - Single S-Filer Deployment', 'In Progress', date)
    Story.CreateHistoryFromExcel('SRMF-303', 'Restore S-Filer Configuration', 'HMP-SRE','To Be Assessed','HMP - Single S-Filer Deployment', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-304', 'Backup S-Filer Databases', 'HMP-SRE','To Be Assessed','HMP - Single S-Filer Deployment', 'In Progress', date)
    Story.CreateHistoryFromExcel('SRMF-305', 'Restore S-Filer Databases', 'HMP-SRE','To Be Assessed','HMP - Single S-Filer Deployment', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-306', 'Backup S-Filer Obfuscated File-Store', 'HMP-SRE','To Be Assessed','HMP - Single S-Filer Deployment', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-307', 'Restore S-Filer Obfuscated File-Store', 'HMP-SRE','To Be Assessed','HMP - Single S-Filer Deployment', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-308', 'Reconnect S-Filer Databases and Obfuscated File-Store', 'HMP-SRE','To Be Assessed','HMP - Single S-Filer Deployment', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-309', 'Check the Health Status of S-Filer', 'HMP-SRE','To Be Assessed','HMP - Single S-Filer Deployment', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-310', 'Check the Metrics of S-Filer', 'HMP-SRE','To Be Assessed','HMP - Single S-Filer Deployment', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-311', 'Document User Creation / Deactivation / Deletion / Key Reset', 'HMP-SRE','To Be Assessed','HMP - Single S-Filer Deployment', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-312', 'Create User & Key-pair', 'HMP-SRE','To Be Assessed','HMP - Single S-Filer Deployment', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-313', 'Document Binding to Platforms', 'HMP-SRE','To Be Assessed','HMP - Single S-Filer Deployment', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-314', 'Bind User/Community/Gateway to Platform', 'HMP-SRE','To Be Assessed','HMP - Single S-Filer Deployment', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-315', 'Receive File from Customer', 'HMP-SRE','To Be Assessed','HMP - Single S-Filer Deployment', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-316', 'Deliver File to Platform', 'HMP-SRE','To Be Assessed','HMP - Single S-Filer Deployment', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-317', 'Receive Report from Platform', 'HMP-SRE','To Be Assessed','HMP - Single S-Filer Deployment', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-318', 'Deliver Report to Customer', 'HMP-SRE','To Be Assessed','HMP - Single S-Filer Deployment', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-319', 'Fail-over S-Filer across Data-Centers', 'HMP-SRE','To Be Assessed','HMP - Redundant S-Filer Deployment', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-320', 'Register S-Filer in the Service Registry', 'HMP-SRE','To Be Assessed','HMP - Redundant S-Filer Deployment', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-321', 'Remove S-Filer from the Service Registry', 'HMP-SRE','To Be Assessed','HMP - Redundant S-Filer Deployment', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-322', 'Upgrade S-Filer Gateway', 'HMP-SRE','To Be Assessed','HMP - Redundant S-Filer Deployment', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-323', 'Upgrade S-Filer Server', 'HMP-SRE','To Be Assessed','HMP - Redundant S-Filer Deployment', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-324', 'Deploy Cluster-Aware S-Filer Update', 'HMP-SRE','To Be Assessed','HMP - Redundant S-Filer Deployment', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-325', 'Fail-over Cluster-Aware S-Filer within Data-Center', 'HMP-SRE','To Be Assessed','HMP - Redundant S-Filer Deployment', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-326', 'Rolling Update of Cluster-Aware S-Filer', 'HMP-SRE','To Be Assessed','HMP - Redundant S-Filer Deployment', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-395', 'Endurance - Ensure application able to run on a stable way for several days', 'AHP, DevExp','2 - High Attention','AHP:Global Integration on ACS', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-396', 'Destructive test/monkey testing', 'DevExp','3 - Normal','AHP:Global Integration on ACS', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-447', 'Deploy a Repeatable Unit (based on acs_integration scripts)', '','2 - High Attention','Create a new Isolation Zone', 'R3 Validated', date)
    Story.CreateHistoryFromExcel('SRMF-448', 'Consolidated SI configuration view', 'SRO, admin_services','3 - Normal','Post incident investigation', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-449', 'Read only DB access - Couchbase', 'CMD, DataStore, admin_services','2 - High Attention','Post incident investigation', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-450', 'Topology view - what version is deployed where', 'CMD, SRO, admin_services','3 - Normal','Post incident investigation', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-451', 'Read only DB access - Oracle', 'CMD, SRE, admin_services','2 - High Attention','Post incident investigation', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-452', 'Display the RU topology', 'SRO','3 - Normal','Display the topology of a DataCenters', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-453', 'Display all the environments available in the DC', '','4 - Low','Display the topology of a DataCenters', 'Out of R3 Scope', date)
    Story.CreateHistoryFromExcel('SRMF-454', 'Display the global topology of all available Datacenters', '','4 - Low','Display the topology of a DataCenters', 'Out of R3 Scope', date)
    Story.CreateHistoryFromExcel('SRMF-455', 'Display the SI configuration of a given POD', 'SRO','3 - Normal','Display the topology of a DataCenters', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-456', 'Display the consolidated SI configuration for a given environment', 'SRO, admin_services','3 - Normal','Display the topology of a DataCenters', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-457', 'Test detection of heap dumps', 'MNR','3 - Normal','Alerting on environment issues', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-458', 'Grant access to core dumps', 'MNR, admin_services','3 - Normal','Post incident investigation', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-459', 'Grant access to heap dumps', 'MNR, admin_services','3 - Normal','Post incident investigation', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-460', 'Alerting on bootstrap component failure', 'CMD, MNR','3 - Normal','Alerting on environment issues', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-461', 'Alert on CPU consumption', 'MNR','3 - Normal','Alerting on environment issues', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-462', 'Alert on MEM consumption', 'MNR','3 - Normal','Alerting on environment issues', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-463', 'Alert on Network Bandwith consumption', 'MNR','3 - Normal','Alerting on environment issues', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-464', 'Alert on SLA failures', 'MNR','3 - Normal','Alerting on environment issues', 'Reopened', date)
    Story.CreateHistoryFromExcel('SRMF-465', 'Alert on RTO - HTTP', 'MNR','3 - Normal','Alerting on environment issues', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-466', 'Alert on CONTROL - HTTP', 'MNR','3 - Normal','Alerting on environment issues', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-467', 'Alert on CONTROL - XML', 'MNR','3 - Normal','Alerting on environment issues', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-468', 'Alert on CONTROL - EDIFACT', 'MNR','3 - Normal','Alerting on environment issues', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-469', 'Alert on RTO - XML', 'MNR','3 - Normal','Alerting on environment issues', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-470', 'Alert on RTO - EDIFACT', 'MNR','3 - Normal','Alerting on environment issues', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-471', 'Alert on disk spaces issues', 'MNR','3 - Normal','Alerting on environment issues', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-472', 'Alert on SWAP memory usage', 'MNR','3 - Normal','Alerting on environment issues', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-473', 'Alerting on LQS/GQS queues', 'MNR','3 - Normal','Alerting on environment issues', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-474', 'Alert on inbound traffic per environment', 'MNR','3 - Normal','Alerting on environment issues', 'Out of R3 Scope', date)
    Story.CreateHistoryFromExcel('SRMF-475', 'Alert on outbound traffic per environment', 'MNR','3 - Normal','Alerting on environment issues', 'Out of R3 Scope', date)
    Story.CreateHistoryFromExcel('SRMF-476', 'Alert on Oracle metrics', 'MNR, SRE','3 - Normal','Alerting on environment issues', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-477', 'Alert on Couchbase metrics', 'DataStore, MNR','3 - Normal','Alerting on environment issues', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-478', 'Restore Couchbase backup - failure', 'DataStore','3 - Normal','Couchbase Backup', 'R3 Delivered', date)
    Story.CreateHistoryFromExcel('SRMF-479', 'Alert on Couchbase backup failures', 'DataStore, MNR','4 - Low','Alerting on environment issues', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-480', 'Alert on Oracle backup failures', 'MNR, SRE','3 - Normal','Alerting on environment issues', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-481', 'Check the isolation of the SIZ is working (no more traffic on it)', '','4 - Low','Isolate an Isolation Zone', 'Out of R3 Scope', date)
    Story.CreateHistoryFromExcel('SRMF-482', 'Check the isolation of the SIZ is working (no more traffic on it) - failure', '','4 - Low','Isolate an Isolation Zone', 'Out of R3 Scope', date)
    Story.CreateHistoryFromExcel('SRMF-483', 'Check the SIZ is taking traffic again', '','4 - Low','Resume the traffic on a Zone', 'Out of R3 Scope', date)
    Story.CreateHistoryFromExcel('SRMF-484', 'Check the SIZ is taking traffic again - failure', '','4 - Low','Resume the traffic on a Zone', 'Out of R3 Scope', date)
    Story.CreateHistoryFromExcel('SRMF-485', 'Have a way to trigger the synchronisation and specify the version', 'FDF','3 - Normal','Force the propagation of a `static` fileset', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-486', 'DML is applied - Success', 'SRE','3 - Normal','Apply an online data change (DML) on Oracle', 'R3 Delivered', date)
    Story.CreateHistoryFromExcel('SRMF-487', 'DML is applied - Failure', 'SRE','3 - Normal','Apply an online data change (DML) on Oracle', 'R3 Delivered', date)
    Story.CreateHistoryFromExcel('SRMF-488', 'DML is fallen back - Success', 'SRE','3 - Normal','Fallback an online data change (DML) on Oracle', 'R3 Delivered', date)
    Story.CreateHistoryFromExcel('SRMF-489', 'DML is fallen back - failure', 'SRE','3 - Normal','Fallback an online data change (DML) on Oracle', 'R3 Delivered', date)
    Story.CreateHistoryFromExcel('SRMF-490', 'List Available Oracle Backups', 'SRE','3 - Normal','Oracle Backups', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-491', 'Backup a Oracle instance - success', 'SRE','3 - Normal','Oracle Backups', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-492', 'Backup a Oracle instance - failure', 'SRE','3 - Normal','Oracle Backups', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-493', 'Restore a Oracle instance - success', 'SRE','3 - Normal','Oracle Backups', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-494', 'Restore a Oracle instance - failure', 'SRE','3 - Normal','Oracle Backups', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-495', 'Backup a Couchbase instance - failure', 'DataStore','3 - Normal','Couchbase Backup', 'R3 Delivered', date)
    Story.CreateHistoryFromExcel('SRMF-496', 'Suspend traffic to a POD - Success', 'SRO','2 - High Attention','Suspend traffic to a POD', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-497', 'Suspend traffic to a POD - Failure', 'SRO','2 - High Attention','Suspend traffic to a POD', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-498', 'SW Load Fallback - Resume traffic to a POD - Success', 'SRO','2 - High Attention','SW Load Fallback - Resume the traffic to a POD', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-499', 'SW Load Fallback - Resume traffic to a POD - Failure', 'SRO','2 - High Attention','SW Load Fallback - Resume the traffic to a POD', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-500', 'Have a way to trigger the synchronisation and specify the version - failure', 'FDF','3 - Normal','Force the propagation of a `static` fileset', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-501', 'DDL on Oracle - Success', 'SRE','3 - Normal','Applying a DDL on Oracle', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-502', 'DDL on Oracle - Failure', 'SRE','3 - Normal','Applying a DDL on Oracle', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-503', 'Fallback DDL on Oracle - Success', 'SRE','3 - Normal','Falling Back a DDL in Oracle', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-504', 'Fallback DDL on Oracle - Failure', 'SRE','3 - Normal','Falling Back a DDL in Oracle', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-505', 'Apply online data change on Couchbase - Success', 'DataStore','3 - Normal','Apply an online data change on Couchbase', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-506', 'Apply online data change on Couchbase - Failure', 'DataStore','3 - Normal','Apply an online data change on Couchbase', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-507', 'Fallback online data change on Couchbase - Success', 'DataStore','3 - Normal','Fallback an online data change on Couchbase', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-508', 'Fallback online data change on Couchbase - Failure', 'DataStore','3 - Normal','Fallback an online data change on Couchbase', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-509', 'Apply new document view on Couchbase - Success', 'DataStore','3 - Normal','Applying a new view document on CouchBase', 'R3 Delivered', date)
    Story.CreateHistoryFromExcel('SRMF-510', 'Apply new document view on Couchbase - Failure', 'DataStore','3 - Normal','Applying a new view document on CouchBase', 'R3 Delivered', date)
    Story.CreateHistoryFromExcel('SRMF-511', 'Remove document view on Couchbase - Success', 'DataStore','3 - Normal','Removing an existing view document from CouchBase', 'R3 Delivered', date)
    Story.CreateHistoryFromExcel('SRMF-512', 'Remove document view on Couchbase - Failure', 'DataStore','3 - Normal','Removing an existing view document from CouchBase', 'R3 Delivered', date)
    Story.CreateHistoryFromExcel('SRMF-514', 'Create a new DB component - Success', 'SRE','2 - High Attention','Create a new DB component - Oracle', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-515', 'Create a new DB component - Failure', 'SRE','2 - High Attention','Create a new DB component - Oracle', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-517', 'Remove a DB component - Success', '','4 - Low','Remove a DB component - Oracle', 'Out of R3 Scope', date)
    Story.CreateHistoryFromExcel('SRMF-518', 'Remove a DB component - Failure', '','4 - Low','Remove a DB component - Oracle', 'Out of R3 Scope', date)
    Story.CreateHistoryFromExcel('SRMF-521', 'Create buckets - Success', '','2 - High Attention','Create new buckets - Couchbase', 'R3 Validated', date)
    Story.CreateHistoryFromExcel('SRMF-522', 'Create buckets - Failure', '','2 - High Attention','Create new buckets - Couchbase', 'R3 Validated', date)
    Story.CreateHistoryFromExcel('SRMF-523', 'Remove buckets - Success', '','4 - Low','Remove buckets - Couchbase', 'Out of R3 Scope', date)
    Story.CreateHistoryFromExcel('SRMF-524', 'Remove buckets - Failure', '','4 - Low','Remove buckets - Couchbase', 'Out of R3 Scope', date)
    Story.CreateHistoryFromExcel('SRMF-526', 'Alerting configuration', 'MNR','2 - High Attention','Capability to configure the framework', 'R3 Delivered', date)
    Story.CreateHistoryFromExcel('SRMF-527', 'Monitoring configuration', 'MNR','4 - Low','Capability to configure the framework', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-528', 'User access management - add', 'CMD','3 - Normal','Capability to configure the framework', 'R3 Delivered', date)
    Story.CreateHistoryFromExcel('SRMF-529', 'User access management - revoke', 'CMD','3 - Normal','Capability to configure the framework', 'R3 Delivered', date)
    Story.CreateHistoryFromExcel('SRMF-530', 'Apply NW changes - Success', 'CMD','3 - Normal','Apply and fallback bootstrap releases', 'R3 Delivered', date)
    Story.CreateHistoryFromExcel('SRMF-531', 'Apply NW changes - Failure', 'CMD','3 - Normal','Apply and fallback bootstrap releases', 'R3 Delivered', date)
    Story.CreateHistoryFromExcel('SRMF-532', 'Apply Security Groups changes - Success', 'CMD','3 - Normal','Apply and fallback bootstrap releases', 'R3 Delivered', date)
    Story.CreateHistoryFromExcel('SRMF-533', 'Apply Security Groups changes - Failure', 'CMD','3 - Normal','Apply and fallback bootstrap releases', 'R3 Delivered', date)
    Story.CreateHistoryFromExcel('SRMF-534', 'Apply Flavors changes - Success', 'CMD','3 - Normal','Apply and fallback bootstrap releases', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-535', 'Apply Flavors changes - Failure', 'CMD','3 - Normal','Apply and fallback bootstrap releases', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-536', 'Apply Routers changes - Success', 'CMD','3 - Normal','Apply and fallback bootstrap releases', 'R3 Delivered', date)
    Story.CreateHistoryFromExcel('SRMF-537', 'Apply Routeurs changes - Failure', 'CMD','3 - Normal','Apply and fallback bootstrap releases', 'R3 Delivered', date)
    Story.CreateHistoryFromExcel('SRMF-538', 'Apply Logical F5 changes - Success', 'CMD','3 - Normal','Apply and fallback bootstrap releases', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-539', 'Apply Logical F5 changes - Failure', 'CMD','3 - Normal','Apply and fallback bootstrap releases', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-540', 'Apply user keys changes - Success', 'CMD','3 - Normal','Apply and fallback bootstrap releases', 'R3 Delivered', date)
    Story.CreateHistoryFromExcel('SRMF-541', 'Apply user keys changes - Failure', 'CMD','3 - Normal','Apply and fallback bootstrap releases', 'R3 Delivered', date)
    Story.CreateHistoryFromExcel('SRMF-542', 'Apply ULF changes - Success', 'CMD, MNR','4 - Low','Apply and fallback bootstrap releases', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-543', 'Apply ULF changes - Failure', 'CMD, MNR','4 - Low','Apply and fallback bootstrap releases', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-544', 'Fallback multiple versions in the past at once', 'CMD, SRO','4 - Low','Apply and fallback bootstrap releases', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-545', 'Capability to specify the version in the past of the framework to load', 'CMD, SRO','4 - Low','Apply and fallback bootstrap releases', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-546', 'Puppet load a new version - success', '','4 - Low','Apply and fallback bootstrap releases', 'Out of R3 Scope', date)
    Story.CreateHistoryFromExcel('SRMF-547', 'Puppet load a new version - failure', '','4 - Low','Apply and fallback bootstrap releases', 'Out of R3 Scope', date)
    Story.CreateHistoryFromExcel('SRMF-548', 'Openshift load a new version - success', 'CMD, SRO','3 - Normal','Apply and fallback bootstrap releases', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-549', 'Openshift load a new version - failure', 'CMD, SRO','3 - Normal','Apply and fallback bootstrap releases', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-550', 'MapR/Hadoop load a new version - success', '','4 - Low','Apply and fallback bootstrap releases', 'Out of R3 Scope', date)
    Story.CreateHistoryFromExcel('SRMF-551', 'MapR/Hadoop load a new version - failure', '','4 - Low','Apply and fallback bootstrap releases', 'Out of R3 Scope', date)
    Story.CreateHistoryFromExcel('SRMF-552', 'Spark load a new version - success', '','4 - Low','Apply and fallback bootstrap releases', 'Out of R3 Scope', date)
    Story.CreateHistoryFromExcel('SRMF-553', 'Spark load a new version - failure', '','4 - Low','Apply and fallback bootstrap releases', 'Out of R3 Scope', date)
    Story.CreateHistoryFromExcel('SRMF-554', 'Kafka load a new version - success', '','4 - Low','Apply and fallback bootstrap releases', 'Out of R3 Scope', date)
    Story.CreateHistoryFromExcel('SRMF-555', 'Kafka load a new version - failure', '','4 - Low','Apply and fallback bootstrap releases', 'Out of R3 Scope', date)
    Story.CreateHistoryFromExcel('SRMF-556', 'Time series DB load a new version - success', 'CMD, MNR','4 - Low','Apply and fallback bootstrap releases', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-557', 'Time series DB load a new version - failure', 'CMD, MNR','4 - Low','Apply and fallback bootstrap releases', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-558', 'Consul load a new version - success', 'SRO','3 - Normal','Deploy a new version of an existing POD', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-559', 'Consul load a new version - failure', 'SRO','3 - Normal','Deploy a new version of an existing POD', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-560', 'Artifactory load a new version - success', '','4 - Low','Apply and fallback bootstrap releases', 'Out of R3 Scope', date)
    Story.CreateHistoryFromExcel('SRMF-561', 'Artifactory load a new version - failure', '','4 - Low','Apply and fallback bootstrap releases', 'Out of R3 Scope', date)
    Story.CreateHistoryFromExcel('SRMF-562', 'acs_server/acs_client load a new version - success', 'SRO','2 - High Attention','Deploy a new version of an existing POD', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-563', 'acs_server/acs_client load a new version - failure', 'SRO','2 - High Attention','Deploy a new version of an existing POD', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-564', 'acs_server/acs_client version fallback - success', 'SRO','2 - High Attention','Deploy a new version of an existing POD', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-565', 'acs_server/acs_client version fallback - failure', 'SRO','2 - High Attention','Deploy a new version of an existing POD', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-566', 'Artifactory version fallback - success', '','4 - Low','Apply and fallback bootstrap releases', 'Out of R3 Scope', date)
    Story.CreateHistoryFromExcel('SRMF-567', 'Artifactory version fallback - failure', '','4 - Low','Apply and fallback bootstrap releases', 'Out of R3 Scope', date)
    Story.CreateHistoryFromExcel('SRMF-568', 'Consul version fallback - success', 'SRO','3 - Normal','Deploy a new version of an existing POD', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-569', 'Consul version fallback - failure', 'SRO','3 - Normal','Deploy a new version of an existing POD', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-570', 'Time Series DB version fallback - success', 'CMD, MNR','4 - Low','Apply and fallback bootstrap releases', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-571', 'Time Series DB version fallback - failure', 'CMD, MNR','4 - Low','Apply and fallback bootstrap releases', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-572', 'Kafka version fallback - success', '','4 - Low','Apply and fallback bootstrap releases', 'Out of R3 Scope', date)
    Story.CreateHistoryFromExcel('SRMF-573', 'Kafka version fallback - failure', '','4 - Low','Apply and fallback bootstrap releases', 'Out of R3 Scope', date)
    Story.CreateHistoryFromExcel('SRMF-574', 'Spark version fallback - success', '','4 - Low','Apply and fallback bootstrap releases', 'Out of R3 Scope', date)
    Story.CreateHistoryFromExcel('SRMF-575', 'Spark version fallback - failure', '','4 - Low','Apply and fallback bootstrap releases', 'Out of R3 Scope', date)
    Story.CreateHistoryFromExcel('SRMF-576', 'MapR/Hadoop version fallback - success', '','4 - Low','Apply and fallback bootstrap releases', 'Out of R3 Scope', date)
    Story.CreateHistoryFromExcel('SRMF-577', 'MapR/Hadoop version fallback - failure', '','4 - Low','Apply and fallback bootstrap releases', 'Out of R3 Scope', date)
    Story.CreateHistoryFromExcel('SRMF-578', 'Openshift version fallback - success', 'CMD, SRO','3 - Normal','Apply and fallback bootstrap releases', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-579', 'Openshift version fallback - failure', 'CMD, SRO','3 - Normal','Apply and fallback bootstrap releases', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-580', 'Puppet version fallback - success', '','4 - Low','Apply and fallback bootstrap releases', 'Out of R3 Scope', date)
    Story.CreateHistoryFromExcel('SRMF-581', 'Puppet version fallback - failure', '','4 - Low','Apply and fallback bootstrap releases', 'Out of R3 Scope', date)
    Story.CreateHistoryFromExcel('SRMF-582', 'Puppet scaling up - success', '','4 - Low','Apply and fallback bootstrap releases', 'Out of R3 Scope', date)
    Story.CreateHistoryFromExcel('SRMF-583', 'Puppet scaling up - failure', '','4 - Low','Apply and fallback bootstrap releases', 'Out of R3 Scope', date)
    Story.CreateHistoryFromExcel('SRMF-584', 'Puppet scaling down - success', '','4 - Low','Apply and fallback bootstrap releases', 'Out of R3 Scope', date)
    Story.CreateHistoryFromExcel('SRMF-585', 'Puppet scaling down - failure', '','4 - Low','Apply and fallback bootstrap releases', 'Out of R3 Scope', date)
    Story.CreateHistoryFromExcel('SRMF-586', 'Openshift scaling up - success', '','4 - Low','Apply and fallback bootstrap releases', 'Out of R3 Scope', date)
    Story.CreateHistoryFromExcel('SRMF-587', 'Openshift scaling up - failure', '','4 - Low','Apply and fallback bootstrap releases', 'Out of R3 Scope', date)
    Story.CreateHistoryFromExcel('SRMF-588', 'Openshift scaling down - success', '','4 - Low','Apply and fallback bootstrap releases', 'Out of R3 Scope', date)
    Story.CreateHistoryFromExcel('SRMF-589', 'Openshift scaling down - failure', '','4 - Low','Apply and fallback bootstrap releases', 'Out of R3 Scope', date)
    Story.CreateHistoryFromExcel('SRMF-590', 'MapR/Hadoop scaling up - success', '','4 - Low','Apply and fallback bootstrap releases', 'Out of R3 Scope', date)
    Story.CreateHistoryFromExcel('SRMF-591', 'MapR/Hadoop scaling up - failure', '','4 - Low','Apply and fallback bootstrap releases', 'Out of R3 Scope', date)
    Story.CreateHistoryFromExcel('SRMF-592', 'MapR/Hadoop scaling down - success', '','4 - Low','Apply and fallback bootstrap releases', 'Out of R3 Scope', date)
    Story.CreateHistoryFromExcel('SRMF-593', 'MapR/Hadoop scaling down - failure', '','4 - Low','Apply and fallback bootstrap releases', 'Out of R3 Scope', date)
    Story.CreateHistoryFromExcel('SRMF-594', 'Spark scaling up - success', '','4 - Low','Apply and fallback bootstrap releases', 'Out of R3 Scope', date)
    Story.CreateHistoryFromExcel('SRMF-595', 'Spark scaling up - failure', '','4 - Low','Apply and fallback bootstrap releases', 'Out of R3 Scope', date)
    Story.CreateHistoryFromExcel('SRMF-596', 'Spark scaling down - success', '','4 - Low','Apply and fallback bootstrap releases', 'Out of R3 Scope', date)
    Story.CreateHistoryFromExcel('SRMF-597', 'Spark scaling down - failure', '','4 - Low','Apply and fallback bootstrap releases', 'Out of R3 Scope', date)
    Story.CreateHistoryFromExcel('SRMF-598', 'Kafka scaling up - success', '','4 - Low','Apply and fallback bootstrap releases', 'Out of R3 Scope', date)
    Story.CreateHistoryFromExcel('SRMF-599', 'Kafka scaling up - failure', '','4 - Low','Apply and fallback bootstrap releases', 'Out of R3 Scope', date)
    Story.CreateHistoryFromExcel('SRMF-600', 'Kafka scaling down - success', '','4 - Low','Apply and fallback bootstrap releases', 'Out of R3 Scope', date)
    Story.CreateHistoryFromExcel('SRMF-601', 'Kafka scaling down - failure', '','4 - Low','Apply and fallback bootstrap releases', 'Out of R3 Scope', date)
    Story.CreateHistoryFromExcel('SRMF-602', 'Time Series DB scaling up - success', '','4 - Low','Apply and fallback bootstrap releases', 'Out of R3 Scope', date)
    Story.CreateHistoryFromExcel('SRMF-603', 'Time Series DB scaling up - failure', '','4 - Low','Apply and fallback bootstrap releases', 'Out of R3 Scope', date)
    Story.CreateHistoryFromExcel('SRMF-604', 'Time Series DB scaling down - success', '','4 - Low','Apply and fallback bootstrap releases', 'Out of R3 Scope', date)
    Story.CreateHistoryFromExcel('SRMF-605', 'Time Series DB scaling down - failure', '','4 - Low','Apply and fallback bootstrap releases', 'Out of R3 Scope', date)
    Story.CreateHistoryFromExcel('SRMF-606', 'Consul scaling up - success', '','3 - Normal','Creation of a new POD', 'R3 Validated', date)
    Story.CreateHistoryFromExcel('SRMF-607', 'Consul scaling up - failure', 'SRO','3 - Normal','Creation of a new POD', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-608', 'Consul scaling down - success', '','3 - Normal','Dismantle an existing POD', 'R3 Validated', date)
    Story.CreateHistoryFromExcel('SRMF-609', 'Consul scaling down - failure', 'SRO','3 - Normal','Dismantle an existing POD', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-610', 'Artifactory scaling up - success', '','4 - Low','Apply and fallback bootstrap releases', 'Out of R3 Scope', date)
    Story.CreateHistoryFromExcel('SRMF-611', 'Artifactory scaling up - failure', '','4 - Low','Apply and fallback bootstrap releases', 'Out of R3 Scope', date)
    Story.CreateHistoryFromExcel('SRMF-612', 'Artifactory scaling down - success', '','4 - Low','Apply and fallback bootstrap releases', 'Out of R3 Scope', date)
    Story.CreateHistoryFromExcel('SRMF-613', 'Artifactory scaling down - failure', '','4 - Low','Apply and fallback bootstrap releases', 'Out of R3 Scope', date)
    Story.CreateHistoryFromExcel('SRMF-614', 'acs_server/acs_client scaling up - success', '','4 - Low','Apply and fallback bootstrap releases', 'Out of R3 Scope', date)
    Story.CreateHistoryFromExcel('SRMF-615', 'acs_server/acs_client scaling up - failure', '','4 - Low','Apply and fallback bootstrap releases', 'Out of R3 Scope', date)
    Story.CreateHistoryFromExcel('SRMF-616', 'acs_server/acs_client scaling down - success', '','4 - Low','Apply and fallback bootstrap releases', 'Out of R3 Scope', date)
    Story.CreateHistoryFromExcel('SRMF-617', 'acs_server/acs_client scaling down - failure', '','4 - Low','Apply and fallback bootstrap releases', 'Out of R3 Scope', date)
    Story.CreateHistoryFromExcel('SRMF-618', 'Access to logs for Puppet', 'MNR','2 - High Attention','Post incident investigation', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-619', 'Access to logs for OpenShift', 'MNR','2 - High Attention','Post incident investigation', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-620', 'Access to logs for MapR/Hadoop', 'MNR','2 - High Attention','Post incident investigation', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-621', 'Access to logs for Spark', 'MNR','2 - High Attention','Post incident investigation', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-622', 'Access to logs for Kafka', 'MNR','2 - High Attention','Post incident investigation', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-623', 'Access to logs for Time Series DB', 'MNR','2 - High Attention','Post incident investigation', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-624', 'Access to logs for Consul', 'MNR','2 - High Attention','Post incident investigation', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-625', 'Access to logs for Artifactory', 'MNR','2 - High Attention','Post incident investigation', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-626', 'Access to logs for acs_client/acs_server', 'MNR','2 - High Attention','Post incident investigation', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-627', 'Deploy a Repeatable Unit (based on acs_cli/acs_server)', '','2 - High Attention','Create a new Isolation Zone', 'Partially Validated', date)
    Story.CreateHistoryFromExcel('SRMF-628', 'Deploy several distinct Repeatable Units', 'CMD, SRO','2 - High Attention','Create a new Isolation Zone', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-647', 'Creation of an environment with ACS server', 'CMD, SRO','2 - High Attention','Create a new instance of ACS', 'Blocked', date)
    Story.CreateHistoryFromExcel('SRMF-661', 'Monitor number of items in queues (in memory)', 'Queues','2 - High Attention','Check the health status of functional queues (LQS/GQS)', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-662', 'Monitor number of items in queue (DB)', 'MNR, Queues','3 - Normal','Check the health status of functional queues (LQS/GQS)', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-664', 'SW Load Fallback - Check the isolation of the RU is working (no more traffic on it)', '','2 - High Attention','SW Load Fallback - Isolate/Resume traffic on a RU', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-665', 'SW Load Fallback - Check the isolation of the RU is working (no more traffic on it) - failure', '','2 - High Attention','SW Load Fallback - Isolate/Resume traffic on a RU', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-666', 'SW Load Fallback - Check the RU is taking traffic again on resume', '','2 - High Attention','SW Load Fallback - Isolate/Resume traffic on a RU', 'Open', date)
    Story.CreateHistoryFromExcel('SRMF-667', 'SW Load Fallback - Check the RU is taking traffic again - failure scenario (consistent state even if on action failure)', '','2 - High Attention','SW Load Fallback - Isolate/Resume traffic on a RU', 'Open', date)
    

class Migration(migrations.Migration):

    dependencies = [
        ('story', '0030_auto_20151002_1542'),
    ]

    operations = [
                  migrations.RunPython(import_history),
    ]
